- build.xml
- composer.json
- composer.lock
Note: TLS issues in Travis force us to use an HTTP endpoint. This should be fixed later when TLS is properly supported on Travis.
See https://github.com/travis-ci/travis-ci/issues/6339 and https://github.com/sensiolabs/security-checker/pull/77#issuecomment-290733113
> Add SensioLabs Security Checker

- app/config/config_dev.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Monolog/Formatter/JsonFormatter.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
All log entries are formatted in JSON format, making it easier to load them into Kibana.
> Provide JSON formatting for logfiles

- ansible/roles/app/templates/xdebug.ini.j2
This was not configured correctly while setting up the development environment in #7 
The only change made to the xdebug configuration is the addition of 
`xdebug.remote_connect_back = 1`
> Configure Xdebug to connect back

- app/config/config_dev.yml
Workaround for unexplained issues with file permissions and
NFS ("session file not created by your uid").
> Save session data to /tmp on development VM

- app/DoctrineMigrations/Version20171002152200.php
- app/config/config.yml
- composer.json
- composer.lock
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/SupplierController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/SupplierRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AdminSwitcherService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/SamlServiceService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/TicketService.php
- tests/unit/Infrastructure/DashboardBundle/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/unit/Infrastructure/DashboardBundle/Service/AdminSwitcherServiceTest.php
- tests/webtests/CreateServiceTest.php
- tests/webtests/Repository/InMemoryServiceRepository.php
- tests/webtests/Resources/config/services.yml
When visiting the `/service/create` route, a new service will be created for the currently active Supplier.
Only the mandatory data is set on the Supplier:
* Id
* Ticket number (a bogus uuid is generated as a stand in for the ticket number that is to be set)
* Supplier Id
The contents of #25 have been included in this PR.
This is is one in a series of pull requests that will implement the feature described in [pivotal #150962638](https://www.pivotaltracker.com/story/show/150962638).
Previous ticket: #25
> Integrate the creation of Services

- src/Surfnet/ServiceProviderDashboard/Application/Command/Supplier/CreateSupplierCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Supplier/EditSupplierCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Supplier/CreateSupplierCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Supplier/EditSupplierCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Exception/EntityNotFoundException.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/SupplierController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/EditSupplierType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/SupplierType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/SupplierRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Supplier/edit.html.twig
- tests/integration/Application/CommandHandler/Supplier/CreateSupplierCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Supplier/EditSupplierCommandHandlerTest.php
- tests/webtests/Repository/InMemorySupplierRepository.php
This part of the requirement is not yet met:
`A supplier cannot edit its own data (name + GUID)`
In my opinion this is more easily implemented when authorisation is implemented in the project. A new story was created to implement this feature at a later stage.
> Provide edit support for Suppliers

- app/AppKernel.php
- app/DoctrineMigrations/Version20171004104623.php
- app/Resources/translations/messages.en.yml
- app/Resources/views/Translation/layout.html.twig
- app/Resources/views/base.html.twig
- app/config/config.yml
- app/config/routing.yml
- build.xml
- composer.json
- composer.lock
- docs/index.md
- docs/translations.md
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Supplier/create.html.twig
See docs/translations.md:
- default translations are stored in yml files inside Resources/translations
- the translation interface allows overriding the default translations
- a new ant target can be used to import new translations after deployment
> Add translation interface

- app/Resources/views/form/fields.html.twig
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Factory/ServiceCommandFactory.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/AttributeType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ContactType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/EditServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/edit.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/SamlServiceService.php
- tests/unit/Application/Factory/ServiceCommandFactoryTest.php
- tests/webtests/CreateServiceTest.php
- tests/webtests/Repository/InMemoryServiceRepository.php
In this PR the edit form was created for Services. Styling has not yet been taken into consideration. Rudimentary support for information popups was added.
The CreateService command was added, it is not yet covered by tests.
This is is one in a series of pull requests that will implement the feature described in [pivotal #150962638](https://www.pivotaltracker.com/story/show/150962638).
Previous PR #27
> Add the Service edit form

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/ServiceList/list.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/TwigExtension/admin_switcher.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/ViewObject/Service.php
- tests/webtests/AdminSwitcherTest.php
- tests/webtests/Repository/InMemoryServiceRepository.php
- tests/webtests/ServiceListTest.php
This commit implements two use cases:
- there are no suppliers created yet: redirect to supplier/create
- no supplier is selected: show a message in the service list
Tests are added for above use cases and for the service list.
> Support dashboard without suppliers or selected supplier

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/SupplierController.php
- tests/webtests/EditSupplierTest.php
There was a problem with a method call on the wrong service. This was introduced during the refactoring of #37 and not providing a suitable web test during development of #22. Both issues have been resolved in this PR.
> Bugfix the Supplier Edit endpoint

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/EditServiceType.php
The archived, environment, status and janusId fields have been removed
from the form type.
> Remove insignificant fields from Service edit form

- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Contact.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Twig/ServiceSwitcherExtension.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Token/SamlToken.php
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/unit/Application/Service/ServiceServiceTest.php
- tests/unit/Infrastructure/DashboardBundle/Service/AuthorizationServiceTest.php
- tests/webtests/CreateServiceTest.php
- tests/webtests/EditEntityTest.php
- tests/webtests/IdentityHeaderTest.php
- tests/webtests/ServiceSwitcherTest.php
- tests/webtests/WebTestCase.php
The switcher is no longer exclusively for administrators. Instead of
showing all services in the database (administrator behaviour) the
switcher is shown when users have access to more than one services.
> Allow regular users to use the service switcher

- app/DoctrineMigrations/Version20171026075111.php
- app/Resources/views/form/fields.html.twig
- docs/ubiquitous_language.md
- src/Surfnet/ServiceProviderDashboard/Application/Command/PrivacyQuestions/PrivacyQuestionsCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/PrivacyQuestions/PrivacyQuestionsCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/PrivacyQuestions.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/PrivacyQuestionsRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/PrivacyQuestionsController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/PrivacyQuestionsRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Privacy/form.html.twig
- tests/unit/Infrastructure/DashboardBundle/CommandHandler/PrivacyQuestions/PrivacyQuestionsCommandHandlerTest.php
- tests/webtests/CreatePrivacyQuestionsTest.php
- tests/webtests/EditPrivacyQuestionsTest.php
This PR will add the Privacy questions to the SP Dashboard. A migration was added to update the database schema. Some styling effort was undertaken.
Todo in next PR
- Publish to Manage
- Add admin feature to toggle the privacy questions for a given Service
> Add privacy questions for Services

- app/scss/components/service_switcher.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Resources/views/Exception/unknownService.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Handler/ProcessSamlAuthenticationHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Exception/UnknownServiceException.php
Instead of showing a generic 'something went wrong' message, we show a
speficic error page for these two situations:
- the user is not member of any teams (empty isMemberOf attribute)
- the user is member of one or more teams, but no service in the
dashboard matches any of the teams
Additionally, the templates for the 'authnfaild' and
'preconditionnotmet' exceptions were rendered using the wrong path,
resulting in a twig error. This has been fixed as well.
> Show error message when user has no access to service

- app/AppKernel.php
The lexik bundle should be registered after the framework bundle so
it can override the default translator.
> Fix broken translation loading

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
- tests/webtests/EditEntityTest.php
**Notes**
Previously these changes where not overwritten as they where entered
by the end user. With this change the imported data is always leading.
No additional checks are performed, the metadata is overwritten with the
newly imported data.
**Checklist**
> Overwrite form values during metadata import

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
**Review notes**
This will set the metadata url field (in the entity edit form) with the entity id. But only when the metadata url field has not been set before.
Reviewers, is this what we want? Or am I solving a non issue?
> Set the MetadataUrl by default on import

- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Application/Command/Mail/MailCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Mail/PublishToProductionMailCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Mail/SendMailCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Mailer/Mailer.php
- src/Surfnet/ServiceProviderDashboard/Domain/Mailer/Message.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityMetadataController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/MailMessageFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Mailer/Mailer.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Mailer/Message.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Mail/published.html.twig
- tests/integration/Application/CommandHandler/SendMailCommandHandlerTest.php
- tests/unit/Application/CommandHandler/Entity/CreateEntityCommandHandlerTest.php
- tests/unit/Application/CommandHandler/PrivacyQuestions/PrivacyQuestionsCommandHandlerTest.php
- tests/unit/Infrastructure/DashboardBundle/Factory/MailMessageFactoryTest.php
- tests/unit/Infrastructure/DashboardBundle/Mailer/MailerTest.php
**Review notes**
Using the MailCommandHandler, messages can be sent to the servicedesk. Each mail should be encapsulated in a MailCommand. Who in turn encapsulates a Message (Swift Mailer Message).
The provided PublishToProductionMailCommand can be executed easily (if you'd like to test this feature IRL) by adding the following code in a controller action of your choise (preferably an action with access to an `Entity`).
```
$messageFactory =  $this->get('surfnet.dashboard.mailer_factory');
$message = $messageFactory->buildPublishToProductionMessage($entity);
$mailCommand = new PublishToProductionMailCommand($message);
$this->commandBus->handle($mailCommand);
```
The message sent is caught by Mailcatcher: http://spdashboard.dev.support.surfconext.nl:1080/
> Add mailer functionality to SP Dashboard

- app/js/components/translation_ui.js
We use .html and .information as suffix for WYSIWYG messages. .help is
not in use so can be safely removed. This prevents accidental match on
'page.header.help'.
> Don't use WYSIWYG editor for keys ending in .help

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
The application, prior to a refactoring, expected the return of a Response. in the case of
a failing Manage interaction no Response object is returned as we
show a flash message on the form.
> Return Form when publishing fails

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
The first condition was the wrong way around, the metadataUrl
should only be set when it's not set yet.
> Actually set the metadataUrl field

- composer.lock
Resolves the following security vulnerabilities:
* CVE-2017-16653: CVE-2017-16653: CSRF protection does not use different tokens for HTTP and HTTPS
http://symfony.com/blog/cve-2017-16653-csrf-protection-does-not-use-different-tokens-for-http-and-https
* CVE-2017-16654: CVE-2017-16654: Intl bundle readers breaking out of paths
http://symfony.com/blog/cve-2017-16654-intl-bundle-readers-breaking-out-of-paths
* CVE-2017-16790: CVE-2017-16790: Ensure that submitted data are uploaded files
http://symfony.com/blog/cve-2017-16790-ensure-that-submitted-data-are-uploaded-files
* CVE-2017-16652: CVE-2017-16652: Open redirect vulnerability on security handlers
http://symfony.com/blog/cve-2017-16652-open-redirect-vulnerability-on-security-handlers
> Update symfony to 3.3.9 and other dependencies

- app/Resources/metadata/attributes.json
Manage expects the friendly name of a requested attribute to be the
last part of the mace urn. For example:
- urn:mace:dir:attribute-def:mail -> mail
- urn:mace:dir:attribute-def:cn -> cn
See: https://github.com/OpenConext/OpenConext-manage/blob/f349da47e1ec83a1f1f399999e13e5e2ef4e47ef/manage-server/src/main/java/manage/format/MetaDataFeedParser.java#L285
> Change attribute friendly names to conform to manage expectations

- app/Resources/metadata/attributes.json
The attribute did not end up in manage after publication because there
was a typo in the friendly name.
> Fix missing shacHomeOrganisationType attribute

- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Generator.php
- tests/unit/Legacy/Metadata/GeneratorTest.php
EngineBlock, manage and the examples in the UI extension specs all use
'mdui' as namespace alias. The dashboard now uses that alias too,
instead of mixing 'ui:' and 'mdui:' in the same document.
> Use 'mdui' namespace alias in metadata XML

- app/AppKernel.php
- app/config/routing.yml
- app/config/security.yml
- composer.json
- composer.lock
- var/SymfonyRequirements.php
- web/config.php
The health and info responses can be requested at respectively: hostname/health and hostname/info
The endpoints are not restricted by firewall rules and thus are publically available. This should be restricted by the load balancer.
As a part of the installation of the bundle, Symfony also updated the
web/config file and updated the SymfonyRequirements checker.
> Install Monitor-bundle 1.0.1

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
- tests/webtests/EntityCopyTest.php
Browsers send the first submit button in the form when the for is
submitted using the enter key. In the case of the entity form, this is
'import'. But this is not user-friendly: when pressing enter we want
the default action to occur:
- enter should save the form when there is a save button
- enter should publish the form if there is only a publish button
This behaviour is implemented by adding a hidden 'default' submit
button on the top of the form.
This commit also fixes a bug where published entities could still be
saved as draft after using the import button.
> Save or publish the form when pressing enter

- app/DoctrineMigrations/Version20180110141503.php
- app/scss/components/actions.scss
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/CreateServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/EditServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/webtests/EntityCreateTest.php
- tests/webtests/EntityListTest.php
SURF-administrators can enable service administrators to create
entities on the production environment without going to test
first.
When the checkbox 'allow production entities' is enabled, users are
allowed to create entities directly for the production environment. To
distinguish creating entities for test and production, the navigation
link 'Add entity' is removed and the 'Add' actions are shown above the
entity list.
> Allow privileged users to create draft entities for production

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
When publishing fails on validation, a flash message is shown telling
the user to scroll down in the form and check the provided values.
> Show flash message when publishing failed

- app/Resources/translations/messages.en.yml
- app/Resources/views/base.html.twig
- app/Resources/views/form/fields.html.twig
- app/scss/excludes/forms.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
**Translation privacy questions 7 & 8**
Label 7 and 8 contained a typo. The 'Valid' keyword was missing from the messages.en.yml file. An update of this value, and a rescan of the translations fixed this issue. 
Fixes #154869772 (466ad78)
**Translatable help link**
Fixes #154920261 (82146d4)
**Privacy labels can contain anchors**
Fixes: #154920044 (8bba053)
**Technical contact translatable**
Fixes #154921698 (ed4dd6b)
> Fix translation relates issues

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- tests/webtests/EntityCreateTest.php
- tests/webtests/EntityListTest.php
**Show service name in entity list**
The `%serviceName%` placeholder can be used in the `entity.list.title translation` to get this feature to work. See `src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml` and/or the web translation.
Fixes #154358882
> Show service name in entity list

- app/js/components/tooltips.js
**Tooltips are now triggered on click**
See story in pivotal for discussion on how and why this change was applied.
Fixes: #154920879
> Trigger tooltips on click instead of hover

- app/scss/excludes/forms.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Parser.php
- tests/webtests/EntityCreateTest.php
- tests/webtests/EntityEditTest.php
- tests/webtests/fixtures/metadata/invalid_metadata.xml
Before this change, xml parser errors where only logged to the app log.
Leaving end users in the dark as to what went wrong during import of their metadata.
This commit changes that, adding a flash message for each parse error.
To prevent display of unwanted xml parser messages (in test), the error
buffer is cleared before validating the XML schema.
To test this feature, simply try to import a malformed SAML SP metadata document and hit the import button. The resulting error messages should help you to fix the violations in the schema.
> Show XML parser errors on metadata import

- app/Resources/views/form/fields.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
While debugging another problem I ran the w3 html schema validation tool on the HTML of the entity edit form. Serveral easily fixable issues arose. This PR fixes those issues:
* the `help` attribute name was renamed to `data-help`.
* removed a rogue `</p>`.
> Small optimalisations after HTML schema validation

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Exception/ParserException.php
- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Parser.php
- tests/webtests/EntityCreateTest.php
- tests/webtests/EntityEditTest.php
- tests/webtests/fixtures/metadata/invalid_metadata_entities_descriptor.xml
- tests/webtests/fixtures/metadata/valid_metadata_entities_descriptor.xml
While importing metadata we did not yet support the occurence of
multiple Entitie**s**Descriptor. This concept allows an SP/IdP to describe
multiple entities in a single metadata file.
For now we only allow the use of EntitiesDescriptor when only a single
entity is described in the document. When more than one documents exist,
an error message is shown, informing the user we do not support this
format.
Two web tests where added to cover these two new situations.
> Support EntitiesDescriptor during import

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Exception/LogoInvalidTypeException.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Exception/LogoNotFoundException.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/validators.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/CurlLogoValidationHelper.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/LogoValidationHelperInterface.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/ValidLogoValidator.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/ValidLogoValidatorTest.php
Logo validation was previously only performed using the getimagesize
function. This function internally resolved the logo and retured either
boolean false (not an image) or an array with the image details.
This was not sufficient as some logos seem to be valid PNG/GIF but are
not available for other reasons. By adding an extra curl based download,
we gain more insighs in the how and why an image might be unavailable.
Extra logging was also added to enable us to debug logo failures more
easily in the future.
@quartje, the error messages can be found [here](https://github.com/SURFnet/sp-dashboard/blob/ecdb1d61a3ec8f0367b33b20de741697ff587a19/src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/validators.en.yml#L1-L3).
> Improve logo validation

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
During rebasing several commits, the nameIdFormat help attribute was
not renamed to the new style: data-help. Resulting in the loss of the
information popup icons in the frontend.
This issue was easily fixed by prepending 'data-' to the attribute.
> Reset the help label on nameIdFormat widget

- app/config/config.yml
- app/config/security.yml
- app/config/services.yml
- composer.json
- composer.lock
- phpunit.xml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Factory/SamlFactory.php
- tests/webtests/EditPrivacyQuestionsTest.php
- tests/webtests/EntityPublishToProductionTest.php
- tests/webtests/Resources/config/services.yml
- tests/webtests/WebTestCase.php
Upgrade to Symfony 3.4
- Some effort was put into getting rid of as many deprecation notices as possible. Not all have been resolved.
- Lexik Translation bundle was updated to support symfony 3.4
When upgrading to version 4, we might need to take a closer look at the way web tests use the DI container. As this results in the most deprecation warnings (reading of private services)
For the translation bundle to work as intended please force update the database schema:
`bin/console doctrine:schema:update --force` as an additional field was added to the `lexik_trans_unit` table.
> Upgrade to Symfony 3.4

- CHANGELOG.md
- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/config.yml
- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/DependencyInjection/Configuration.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/DependencyInjection/DashboardSamlExtension.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
- tests/unit/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProviderTest.php
The configuration has been renamed and rebuild to allow setting more
than one admin team.
The Saml Authentication provider now also supports multiple teams. This,
by simply iterating over the configured teams. And leaving the original
logic unchanged.
> Support multiple admin teams

- app/js/components/validation.js
We only want form validation on email fields, and possibly when
submitting the form for publication. So refrain from using Parsley when
user presses the import, save or cancel buttons. These buttons would
trigger form validation in unwanted situations.
> Prevent validation on unwanted events

- ansible/roles/spdashboard/files/makeRelease.sh
- app/js/components/validation.js
Thanks to an explanation found on the webpack encore issues page:
> Lyrkan: on Aug 15, 2017
>
> So, looking back at it a bit more, the version of Webpack shipped with
> Encore currently installs uglifyjs-webpack-plugin v0.4.6 which uses
> uglify-js v2.8.29. This version of uglify-js doesn't support ES6 and,
> since vendors don't go through Babel it fails if you require something
> from them written using ES6. It works using the files in dist since
> they have already been processed by Babel using the ES2015 preset.
SO the solution to our problem was not to include Parsley from the 'src'
folder, but to read it from the ES2015 compliant 'dist' folder.
The makeRelease.sh was also updated to run encore in production mode,
reverting the previously made change.
> Re-enable running encore in production mode

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/GeneratorInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityMetadataController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
The problem was two-fold:
1. When publising an entity already existing in manage, entity fields
such as 'active' and 'allowall' were always reset to their original
value. This commit changes the behaviour to only send the values on
the initial push to manage, and not on subsequent pushed.
2. The merge-write implementation was sending a list of metadata
fields, suggesting all metadata fields not in that list should be
deleted. This has been solved by using the flat format so all fields
not known to the dashboard are untouched.
See [pivotal](https://www.pivotaltracker.com/story/show/157119861).
> Don't overwrite fields when updating existing entities

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Http/HttpClient.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/ValidEntityIdValidatorTest.php
- tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
- tests/unit/Infrastructure/Manage/Client/QueryClientTest.php
- tests/unit/Infrastructure/Manage/Http/HttpClientTest.php
- tests/webtests/Resources/config/services.yml
This PR fixes a misleading error message (referring to a manage ID with "entityId") and makes sure all requests and responses to manage are logged when an error occurs.
See [pivotal](https://www.pivotaltracker.com/story/show/157657124).
> Log all requests and responses to manage

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ContactType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
When a value is entered, it must be valid but the form can always be
saved with empty fields. Requiredness is checked on publication.
> Make all entity fields optional

- composer.lock
This resolves the following security vulnerabilities:
symfony/symfony (v3.4.4)
------------------------
* CVE-2018-11407: CVE-2018-11407: Unauthorized access on a misconfigured LDAP server when using an empty password
https://symfony.com/cve-2018-11407
* CVE-2018-11386: CVE-2018-11386: Denial of service when using PDOSessionHandler
https://symfony.com/cve-2018-11386
* CVE-2018-11406: CVE-2018-11406: CSRF Token Fixation
https://symfony.com/cve-2018-11406
* CVE-2018-11408: CVE-2018-11408: Open redirect vulnerability on security handlers
https://symfony.com/cve-2018-11408
* CVE-2018-11385: CVE-2018-11385: Session Fixation Issue for Guard Authentication
https://symfony.com/cve-2018-11385
> Update symfony to 3.4.11

- app/js/components/validation.js
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/AttributeType.php
TextTypes with the 'keep talking' feature can now also be set with an
optional word-threshold attribute. Should be set with an integer value.
When the attribute is omitted the default (set to 10) word threshold
will be used.
The attribute motivation TextTypes are now configured to set a three
word input warning threshold.
See pivotal https://www.pivotaltracker.com/story/show/158141820
> Introduce a word-threshold configuration option

- ansible/roles/spdashboard/templates/spdashboard.conf.j2
PHP under fcgi doesn't parse the Authorization header into PHP_AUTH_*
$_SERVER variables. Symfony requires this to work. This commit changes
the vhost configuration to copy the contents of Authorization into an
environment variable HTTP_AUTHORIZATION.
EngineBlock API already uses this rule in its configuration.
> Allow basic HTTP authentication for SP dashboard vhost

- phpmd.xml
The CouplingBetweenObjects rule now has a threshold of 20, which is
the same threshold as PMD itself uses.
> Loosen PHPMD CBO threshold

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
All service providers should use RSA-SHA256, if new service providers
don't support it, we want to know about it as early as possible.
See: https://www.pivotaltracker.com/story/show/158296323
> Use RSA-SHA256 as signature algorithm for service providers

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/PublishEntityProductionCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Exception/NotAuthenticatedException.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/MailMessageFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Mail/published.html.twig
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
- tests/unit/Infrastructure/DashboardBundle/Factory/MailMessageFactoryTest.php
- tests/webtests/EntityPublishToProductionTest.php
The contact information (display name + email address) is shown in the
e-mail sent when publishing an entity to production.
...
Link to Metadata: https://spdashboard.dev.support.surfconext.nl/entity/metadata/2f4ee070-6f00-11e8-88f4-97d5d5b83948
Published by: John Doe <j.doe@example.com>
...
See: https://www.pivotaltracker.com/story/show/157114703
> Add contact information to production publication e-mail

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/CurlLogoValidationHelper.php
The timeout is now set at ten seconds for both the connect timeout
and the entire running time of the curl request.
:warning: The build fails on the security checker. The recommended updates will be installed in another PR. Either merge this PR with the failing build or rebase onto afore mentioned PR.
See: https://www.pivotaltracker.com/story/show/158383467
See: https://github.com/SURFnet/sp-dashboard/pull/147 (composer update)
> Set curl timeout on logo downloads

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/webtests/EditServiceTest.php
- tests/webtests/WebTestCase.php
First review #148 .. #152 
This adds a web test to the test suite that verifies the correct determination of the privacy questions filled service status option.
>  Verify privacy questions are displayed correctly 

- app/DoctrineMigrations/Version20181107134447.php
- app/js/application.js
- app/js/components/service_status_interactions.js
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceStatusService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/CreateServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/EditServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/PrivacyQuestionAnsweredType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/webtests/EditServiceTest.php
- tests/webtests/WebTestCase.php
:warning: Review and merge #149 first!
The privacy questions service status radio group is disabled when
privacy questions are not enabled for the service.
> Disable privacy questions service status

- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceStatusService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/CreateServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/EditServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/EntityPublishedType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/unit/Application/Service/ServiceStatusServiceTest.php
- tests/webtests/EditServiceTest.php
The service reads the entities for the service and checks if any are published or drafted. If none of the above the status 'no' is returned, in the other cases 'yes' or 'in progress' are returned.
See: https://www.pivotaltracker.com/story/show/161341178
> Display entity published state on service forms

- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- tests/webtests/ServiceOverviewTest.php
Some decisions have been made which might need adjustment later on:
1. The service names have been made links to enable us to switch to that service (to get to their entities & privacy questions)
2. The service overview has been made the default route at (/) And the previous default (entities overview) is now available at /entities.
3. Service entities are fed into the twig template. A more template friendly object might be required at some point.
:warning: This PR is built on top of #158
> Introduction of the services overview page

- phpunit.xml
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Twig/ServiceSwitcherExtension.php
- tests/webtests/EntityListTest.php
- tests/webtests/ServiceOverviewTest.php
- tests/webtests/ServiceSwitcherTest.php
This role will be using the more user friendly overview page that is
yet to be created. This change rolls back the previous adjustment where
contacts with multiple services leveraged the admin service switcher.
See: https://www.pivotaltracker.com/story/show/161719597
See: Task 1 of #161719597
> Prevent ROLE_USER from using service switcher

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- tests/webtests/EntityPublishToProductionTest.php
The production entities should always be removed from local database
storage after they have been successfully published to manage (prod).
In doing so I've tried to make the publishEntity of the
EntityControllerTrait a bit more understandable.
See: [Task 4 of #161679714](https://www.pivotaltracker.com/story/show/161679714)
> Remove published entity from database

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
- tests/webtests/CommandHandler/MockPublishEntityToProductionCommandHandler.php
- tests/webtests/EntityPublishToProductionTest.php
- tests/webtests/Resources/config/services.yml
The manage-prod instance is used for this purpose. The additional
coin:exclude_from_push attribute is added to production entities. And
will ensure the entity will end up in the staging area in manage.
To test this functionally first install Manage production.
See https://www.pivotaltracker.com/story/show/161679714
:warning: Built on top of #159
> Publish production entities to manage

- app/js/application.js
- app/js/components/service_form.test.ts
- app/js/components/service_form.ts
- app/js/components/service_status.test.ts
- app/js/components/service_status.ts
- app/scss/components/service_status.scss
- build.xml
- jest.config.js
- package.json
- src/Surfnet/ServiceProviderDashboard/Application/Assembler/ServiceStatusAssembler.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ServiceStatusDto.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/Api/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
- tests/unit/Application/Assembler/ServiceStatusAssemblerTest.php
- tests/webtests/ServiceOverviewTest.php
- tmp.json
- tsconfig.json
- tslint.json
- yarn.lock
On the servicepage the actual service state should be made visible
so it should become more intuitive for the enduser where in the
process the service connection request is.
https://www.pivotaltracker.com/story/show/161719597
~~There are still some tasks that need to be done:~~
> Show the actual service state on the home

- src/Surfnet/ServiceProviderDashboard/Domain/Repository/EntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Console/CleanOldProductionEntitiesCommand.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/EntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/webtests/CleanOldProductionEntitiesCommandTest.php
Because of the separation of manage in a production and a test
environment the old published to production entities needed to be
cleaned from the local database.
https://www.pivotaltracker.com/story/show/162051868
> Remove published prod entities unknown to manage

- app/Resources/views/modal.html.twig
- app/js/application.js
- app/js/components/modal.js
- app/js/components/modal.ts
- app/js/type_definitions.ts
- app/scss/components/form.scss
- app/scss/components/modal.scss
- app/scss/pages/choose_entity_type.scss
- docs/index.md
- docs/third_party_packages.md
- package.json
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Command/Entity/ChooseEntityTypeCommand.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ChooseEntityTypeType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
- tests/webtests/EntityListTest.php
- yarn.lock
In this dialog, the user can select the option to add either a SAML2 or OpenID connect entity.
The scope of this PR is to add the screen and integrate it into the current workflow untill the rendering of the entity create form. This will be taken care of in an upcoming PR.
Details: https://www.pivotaltracker.com/story/show/161720049
> Add the entity type dialog screen

- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Service/IssueService.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
- tests/unit/Infrastructure/Jira/Service/IssueServiceTest.php
Nine fields are set on the ticket. This is still a hypothetical change
which has not yet been tested on an actual Jira installation.
The custom fields for the APPLICANT_NAME|EMAIL are still to be set.
See:
https://www.pivotaltracker.com/story/show/162124271/comments/196880347
> Set the required Jira ticket fields

- ansible/roles/spdashboard/defaults/main.yml
- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/parameters.yml.dist
- composer.json
- composer.lock
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/TicketRepository.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/JiraServiceFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Service/IssueService.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
- tests/unit/Infrastructure/Jira/Factory/JiraServiceFactoryTest.php
- tests/unit/Infrastructure/Jira/Service/IssueServiceTest.php
Using the php-jira-rest-client, a Jira issue creation service has been built to provide proof of concept. 
This service for now is able to create a simple jira ticket. The final implementation awaits input from the product owners.
https://www.pivotaltracker.com/story/show/162191079
> Introduction of Jira integration

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/JiraServiceFactory.php
- tests/unit/Infrastructure/Jira/Factory/JiraServiceFactoryTest.php
Jira logged to it's own logger instance if no logger instance was passed
to the JiraClients (in our case the IssueService).
The Client (Service) factory is now set up with the application logger
and can pass it to the constructor of the services it will build.
Also see task 4 from https://www.pivotaltracker.com/story/show/162124271
> Make sure Jira log entries are logged correctly

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
The Jira service might throw an exception whenever it was unable to
create/connect/.. these exceptions where not yet caught by the command
handler. They now are, and a flash message is shown to the user. The
original log message is saved with the logger.
> Improve Jira error reporting to end users

- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
Both the summary and description have been made translatable. This
allows the application admin to set the translations for these texts
in the translation web  interface.
The description can be set with three parameters:
- %applicant_name%
- %applicant_email%
- %entity_name%
And the summary can use:
- %entity_name%
> Translate Jira issue summary and description

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoter.php
- tests/unit/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoterTest.php
The possibility that a manage entity could be null was not taken into
consideration. This change now tests if the entity was found, if not,
it will deny access.
See https://www.pivotaltracker.com/story/show/162605255
> Make ManageEntityAccessGrantedVoter more robust

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Handler/ExplicitSessionTimeoutHandler.php
The url parameter was missing for the entities overview. But now we use
the service overview so that isn't needed anymore.
> Fix url in session timeout handler

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ChooseEntityTypeType.php
Because oidc is currently not supported it shouldn't temporarily
be possible to select oidc as an option.
> Temporarily disable the oidc entity type in modal

- app/js/components/modal.ts
- app/js/type_definitions.ts
- app/scss/components/modal.scss
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/oidcConfirmationModal.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
The modal window is displayed after a successful publication to manage.
This is done only once. After the action was performed, the in memory
(session) clone is removed from the session.
This PR are the commits from #195 after the add oidc changes were finished.
> Add oidc confirmation screen after publish

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
Because the entities of oidc and saml are a bit different we need
different translations in order to reflect these differences to the
enduser.
> Add oidc specific translations

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
The state translations of the entities should be changed to reflect the
actual state much better for sp's. Therefore translations are added.
The changes from #207 are used to prevent merge conflicts because
the entityties were split based on environment.
> Change the state translations

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
The client secret needs to be generated only once per environment.
Currently this is done on every publish action. This should not happen.
> Fix to generate only once per environment a client secret

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
The client id should not be changed. This commit will fix that, so the
clientId could be only set once when adding the oidc entity.
> Prevent oidc clientId from updating

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
The character : needs to be replaced by a @ when storing to manage.
> Fix oidc clientId encoding

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/oidcConfirmationModal.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/webtests/EntityCreateOidcTest.php
The clientId when publishing the entity to production had a : replaced
with @. This shouldn't be done, and this commit will fix that behaviour.
> Fix oidc clientId when publishing to production

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/LoadEntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
The playground checkbox didn't work as expected and should add a
playground url when checked and should tick the checkbox and remove
the redirect uri from the form when the redirect uri gets returned from
manage.
> Fix playground redirect uri

- package.json
- yarn.lock
To harden against  CVE-2018-14732
More information: https://nvd.nist.gov/vuln/detail/CVE-2018-14732
> Upgrade npm dependencies

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/PrivacyQuestionsController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/cloneAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/copyAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/deleteAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/editAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
- tests/webtests/EntityCopyTest.php
- tests/webtests/EntityCreateOidcTest.php
- tests/webtests/EntityCreateSamlTest.php
- tests/webtests/EntityDeleteTest.php
- tests/webtests/EntityListTest.php
The given service of an entity is not set for certain entity routes
which will throw an exception because a service is needed. This was not
an issue before because the active service was set in the session. But
because we now have overview pages with multiple services. We should
add the service to the route to know the active service on forehand.
> Fix routes missing services

- .travis.yml
- build.xml
- composer.lock
- package.json
- yarn.lock
Three chores have been addressed in this PR
1. yarn audit now runs with the security tests and fails if a known vulnerability is found
2. a known vulnerability was fixed
3. the Sensiolabs security checker was upgraded to the latest.
See https://www.pivotaltracker.com/story/show/163251708
> Improve security tests

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Mail/jiraPublicationFailed.html.twig
In the mail template to notify the support desk when a publication
has failed there is a `dump` method. However this method is not
supported in the prod environment. So this is removed.
> Fix the dump method in twig template for prod

- build.xml
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/TicketService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
When re-publishing an entity that was previously published to production
(with a Jira ticket for the SD), the ticket must not be created for a
second time.
By trying to find the ticket before creating a new one we can prevent
the creation of duplicates.
https://www.pivotaltracker.com/story/show/163385254
>  Ensure Jira tickets are created once 

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
The : in an oidc entityId should be replaced with a @. This was done
on other pages except on the entity detail page were it was missing in
the corresponding viewobject.
https://www.pivotaltracker.com/story/show/163417371
> Fix oidc client id on detail page

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityOidcConfirmation.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
The : in an oidc entityId should be replaced with a @. This was done
on other views except for the oidc confirmation popup were it was
missing in the corresponding viewobject.
https://www.pivotaltracker.com/story/show/163417513
> Fix oidc client id on confirmation popup

- CHANGELOG.md
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
When a new entity is published, the manage id is not yet known and
a Jira issue is not previously published. This commit ensures we only
try to find a jira issue of the manage id is set.
https://www.pivotaltracker.com/story/show/163385254/comments/198784169
> Prevent new entities for checking Jira ticket

- CHANGELOG.md
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/admin_overview.html.twig
- tests/webtests/ServiceOverviewTest.php
The admin user now is faced with a potential 504 error after logging on
to the application. As the service overview page is causing much data
to load for the admin user. In production, over 150 SP's are loaded on
this page including all their entity information.
This does not work out! The easy fix for now is simply rendering a
blank page with a small instruction to the admin user, to use the
service switcher and switch to the desired service that way.
For now the simplest of solutions is chosen (render a different template
if you are an admin user. This could and will be improved upon in an
upcoming development effort.
https://www.pivotaltracker.com/story/show/163691688
> Provide a custom service overview for admin

- CHANGELOG.md
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
The array that is passed along to manage should be a list, not a map.
If the php indexes are updated along the way, by adding/removing items
from the form. The index order might not be sequentially pristine. This
causes JSON encode to generate a map instead of a list.
By resetting the list before publishing, this problem should be remedied
https://www.pivotaltracker.com/story/show/163646662
> Correctly publish OIDC redirectUris to Manage

- src/Surfnet/ServiceProviderDashboard/Application/Dto/EntityDto.php
The env and status fields where entered into the EntityDto the other
way around. Causing the donut to not correctly display entity
publication states.
https://www.pivotaltracker.com/story/show/163732191
> Replace environment with status

- build.xml
This does not mean we are ignoring vulnerabilities in JS dependencies,
but at the moment we are not yet able to easily fix the 62
vulnerabilities reported. We cannot yet migrate to Jest 24 due to a lack
of TS support. I opened a ticket to fix this once TS support lands for
Jest 24.
https://www.pivotaltracker.com/story/show/164103245
> Do not failonerror with yarn audit

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- tests/webtests/ServiceAdminOverviewTest.php
- tests/webtests/ServiceOverviewTest.php
The service switcher should now redirect to the service overview (donut) overview page for the selected service. This is basically a filtered view on the existing donut overview page which showed all available services for the admin user.
See commits for details about the changes that are introduced.
https://www.pivotaltracker.com/story/show/163752485
> Change service switcher behavior

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
The status was not updated on the Service entity, The first time when
the status is not yet set to either requested or active, the status
is updated.
https://www.pivotaltracker.com/story/show/163732191
> Update the production connection status on publication

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- tests/webtests/ServiceOverviewTest.php
Change route on overview page for non admins to the entity detail
page. This should be changed because the currently used route should
not be accessible for non admins. This in order to prevent an exception
when trying to access the edit page for non admins when not allowed.
> Change detailed route on overview page to prevent 403

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/QueryEntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
- tests/unit/Application/Service/EntityServiceTest.php
All entities were fetched with the 'testaccepted' state. This resulted
in entities not being fetched after they where published with
'prodaccepted'. This fix will get the entities based on the state
configured in the parameters.yml.
> Fix manage query state for prod

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
Translations are no longer reused between the two entity types. This was fixed for the attribute information balloon translations and several titles on the entity detail screens.
Note to the releaser/reviewer.
The original attribute information balloon texts have been removed / replaced with saml20 and oidc counterparts. For example: 
`entity.edit.information.givenNameAttribute` is broken up into: `entity.edit.information.saml20.givenNameAttribute` and `entity.edit.information.oidc.givenNameAttribute`
> Update translations for SAML20 and OIDC

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailTextField.html.twig
When clicking on the secret to copy it a space was selected before the
secret and this is very helpful. Therefore removed the spacing.
> Prevent a space in the secret when copying

- src/Surfnet/ServiceProviderDashboard/Application/Service/LoadEntityService.php
- tests/unit/Application/Service/LoadEntityServiceTest.php
The entity was copied but used the wrong environment so the playground
url from test was added to the redirect uri's and the checkbox was
unchecked.
> Fix the playground url after copy to production

- app/js/components/validation.js
The regex for the URN validator was faulty and a slash was missing
escaping. This resulted in a false negative when validating URN's.
> Fix urn validator regex

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailBooleanField.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailListField.html.twig
- tests/webtests/EntityDetailTest.php
If the entity protocol is oidc, the oidc attributes are shown on the entity detail screen. This entails:
1. A list of the redirect uris (new: list field)
2. The grant type (text field)
3. Playground enabled (new: boolean field)
The field labels are being made into translatable messages. They are key -> translation:
- entity.detail.metadata.redirect_uris: Redirect URIs
- entity.detail.metadata.grant_type: Grant type
- entity.detail.metadata.playground_enabled: Playground enabled?
See: https://www.pivotaltracker.com/story/show/164598856
> Show OIDC items on entity details

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailAttributeField.html.twig
- tests/webtests/EntityDetailTest.php
Attributes without motivation (possible for drafts and test entities)
did not show up on the entity detail screen. They are now displayed.
When no motivation is set, a translatable 'no motivation set' message
is rendered.
See: https://www.pivotaltracker.com/story/show/165597382
> Show motivationless attributes on entity detail

- app/Resources/translations/messages.en.yml
- app/Resources/views/base.html.twig
The `contact` and `privacy` links were set to a hard '/'. This is addressed by setting adding them to the translations. Allowing overriding these URL's from the web translation interface. Some dummy defaults are set in the messages.en.yml.
See: https://www.pivotaltracker.com/story/show/165965469
> Add translatable footer links

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
The name of the field on the srevie form needs to be changed to be
describe more logically what the purpose of the field is.
> Rename 'team name' to 'team identifier'

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ContactType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
The placeholders of the contact email address fields should be
translatable. So a placeholder is added and a translation is added.
> Add translatable contact email placeholder

- src/Surfnet/ServiceProviderDashboard/Application/Assembler/ServiceStatusAssembler.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceStatusService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/unit/Application/Assembler/ServiceStatusAssemblerTest.php
- tests/unit/Application/Service/ServiceStatusServiceTest.php
If a service has no entities the donut should reflect that. So it
must not look if any progess so far has been made.
> Change the donutstate with empty service

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- tests/webtests/ServiceDeleteTest.php
The relationship between service and privacy question is now configured to apply a cascading delete on privacy question entities when a service is removed. In addition, Doctrine is instructed to remove orphaned entities.
**Bugreport:** https://www.pivotaltracker.com/story/show/165237921
**See:** https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#transitive-persistence-cascade-operations
**See:** https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/working-with-associations.html#orphan-removal
> Cascade delete privacy questions on service removal

- app/config/config.yml
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Middleware/DoctrineTransactionMiddleware.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/unit/Infrastructure/DashboardBundle/Middleware/DoctrineTransactionMiddlewareTest.php
Add transactions to the command bus. This, to prevent duplicate entities when storing entities and an unexpected exception occurs.
> Add transactions middleware to commandbus

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/UpdateEntityAclCommand.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/IdentityProvider.php
- tests/unit/Infrastructure/Manage/Client/IdentityProviderClientTest.php
- tests/unit/Infrastructure/Manage/Client/fixture/identity_provider_response.json
When testing on the test server it occurred that the `name:en` is
mandatory and `name:nl` optional. This will fix this so it would be
possible to edit acl's if idp's don't have a `name:nl` set.
https://www.pivotaltracker.com/story/show/165965483
> Fix idp validation from manage result

- app/DoctrineMigrations/Version20190605093154.php
A default column was missing what resulted in a service which could not be saved because a validation error occurred and was not visible if you tried to save the service with type=institute.
See https://www.pivotaltracker.com/story/show/166083724
> Add default value for `representative_approved` column.

- app/scss/components/modal.scss
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/ResetOidcSecretCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- tests/integration/Application/CommandHandler/Entity/ResetOidcSecretCommandHandlerTest.php
Whenever a published OIDC entity was using the client reset function, a duplicate local entity was saved to the database. This entity could not be removed from the application, as it will attempt to removed from Manage (as the production state is published). To fix this, the manage id had to be set on the local copy that is only temporarily used to carry the new client id secret.
In addition to this bugfix, a visual regression was fixed as well in 40570fc.
See: https://www.pivotaltracker.com/story/show/165673435
> Do not save a local duplicate upon client reset

- app/config/config.yml
- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Manage/ConfigFactory.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Manage/PublicationStatus.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/Configuration.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/IdentityProviderClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Application/Service/EntityAclServiceTest.php
- tests/unit/Application/Service/EntityServiceTest.php
- tests/unit/Infrastructure/Manage/Client/IdentityProviderClientTest.php
- tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
The `prodaccepted` state was used by default when retrieving IdP entities for display on the ACL screen. Now, we use the configured workflow state to filter the IdP results on.
This PR starts off with some housekeeping. The first commit (390213b) updates the way the workflow is configured. Previously the workflow state could be set for different intentions (create/update). This is not the way we use this feature. Instead of using this approach, setting a single workflow state per environment is now implemented.
The second commit then proceeds to read the configured workflow state from the manage configuration. This configuration is injected on the IdPclient.
See: https://www.pivotaltracker.com/story/show/165965483
> Consider IdP workflow state when retrieving IdP's for ACL action

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Value/DateTime.php
During a migration an incorrect invalidArgument was imported, resulting
in a fatal error if a non string was passed into the method.
The error was also never thrown, which is now also fixed
> Import correct invalid argument and throw it

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/IssueCollection.php
- tests/unit/Domain/ValueObject/IssueCollectionTest.php
- tests/unit/Infrastructure/DashboardBundle/Jira/Repository/IssueRepositoryTest.php
Instead of indexing the Jira issues on the corresponding manage id, they were indexed on Jira key. This caused the status not being updated.
This is hard to test in a development environment, as we use a tests stand in for Jira interaction. And the issue did not surface in that solution.
> Ensure the issues are indexed on Manage id

- .travis.yml
This is done in order to be able to test behavior on php 7.3 to
explore possible php migration issues.
> Test PHP 7.3 with Travis

- app/config/security.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoter.php
The translation endpoint could be reached if a user was logged in
and wasn't restricted to Administrators only.
The access_control is therefore changed and a change in a voter was
needed to allow validation of the endpoint.
https://www.pivotaltracker.com/story/show/167063760
> Fix the translations acl

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoter.php
- tests/unit/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoterTest.php
- tests/webtests/EntityDeleteTest.php
The voter used on the entity delete endpoint didn't work as expected
for the administrator role because the role was validated against a
string and not a Role.
Also the endpoint didn't take the result into account from the isGranted
method and the isGranted method din't throw an exception either. Both
issues are now fixed.
https://www.pivotaltracker.com/story/show/167062944
> Fix the entity delete acl

- app/Resources/views/Translation/layout.html.twig
- app/config/security.yml
- composer.json
- composer.lock
- docs/translations.md
- src/Surfnet/ServiceProviderDashboard/Application/Assembler/ServiceStatusAssembler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityAcl/acl.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/secretResetModal.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/oidcConfirmationModal.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/publishedProduction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/publishedTest.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Privacy/form.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/admin_overview.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Twig/WysiwygExtension.php
The lexik translation bundle  doesn't input validate the wysiwyg
entries. Because it's third party software it's hard to get it into
the bundle. Therefore we decided to validate the output.
To do so a wysiwyg filter is introduced and the documentation is
updated accordingly.
Also the ServiceStatusAssembler needed to be updated in order to
escape the json returned to render the service status donut.
---
Boyscouted:
Add ajax.googleapis.com to CSP whitelist to load external assets
for the Lexik translation bundle.
> Escape the wysiwyg translations

- ansible/roles/manage-server-prod/defaults/main.yml
- ansible/roles/manage-server-prod/files/metadata_configuration/oidc10_rp.schema.json
- ansible/roles/manage-server-prod/files/metadata_configuration/saml20_idp.schema.json
- ansible/roles/manage-server-prod/files/metadata_configuration/saml20_sp.schema.json
- ansible/roles/manage-server-prod/files/metadata_export/saml20_sp.xml
- ansible/roles/manage-server-prod/files/metadata_templates/oidc10_rp.template.json
- ansible/roles/manage-server-prod/templates/application.yml.j2
The Ansible roles in this project contain a copy of the manage role in OpenConext-deploy. This is needed to create a second Manage instance on the development VM.  Some changes have been made in OpenConext-deploy to accommodate the provisioning of OIDCNG clients.  This PR merges the changes from OpenConext-deploy back to the Ansible role "manage-prod"
> Update Manage to a newer version and enable OIDC TNG

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
- tests/unit/Infrastructure/DashboardBundle/Jira/Repository/IssueRepositoryTest.php
When loading an empty issue mock file to get a working implementation without the use of a working Jira instance, a mock file was used.
If this file was empty an exception was thrown because the data was then not parsed to an empty array but to null which triggered input validation. This is now fixed.
> Prevent error when loading an empty issue mock file

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Twig/WysiwygExtension.php
This is done in order to prevent warning because it will try
to write to `/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer`
which will generate a warning on production.
https://www.pivotaltracker.com/story/show/167222617
> Disable the htmlpurifier cache

- ansible/roles/spdashboard/defaults/main.yml
- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/parameters.yml.dist
- docs/jira.md
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DashboardBundle.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/Compiler/IssueRepositoryCompilerPass.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/DashboardExtension.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services_dev.yml
We sometimes do not have a working Jira configuration at the ready. In those cases the test stand-in is a useful fallback measure. Previously the test and development environment by default used this stand-in. This has now been changed to become a feature flag.
This flag can be set to true/false in the parameters.yml
The filePath of the test file has also been made into a configuration option while at it.
https://www.pivotaltracker.com/story/show/167315333
> Make Jira test mode configurable

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- tests/webtests/EntityCreateOidcngTest.php
Previously all oidcng entities would be set with grant type `authorization_code`. Now the user can choose between the `authorization_code` and implicit. The oidcng behaviour for the grant types is now aligned with that of the oidc type.
https://www.pivotaltracker.com/story/show/167511241
> Enable an additional grant type

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
Sending the client secret a second time (null) will cause Manage to spit out a 500 error. Easily remedied by testing if the client secret is set. If it is not, we no longer pass it to Manage API.
https://www.pivotaltracker.com/story/show/168049212
> Refrain from sending a NULL secret to Manage

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveSamlEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- tests/webtests/EntityCreateSamlTest.php
The OIDCng contributing users are now able to specifiy the subject type of their entity. Which is analog to the SAML20 NameIdFormat.
More details in: https://www.pivotaltracker.com/story/show/167511146
> Allow selection of Subject Type (NameIdFormat)

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- tests/integration/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandlerTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/webtests/EntityCreateOidcngTest.php
The EduPersonTargettedID attribute is always requested for oidcng
entities. The command tasked with saving the entities enables the epti
attribute by default.
See: https://www.pivotaltracker.com/story/show/167511328
> Request EPTI by default for each OIDC TNG entity

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- tests/integration/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandlerTest.php
Previously only the placeholder value was shown on the field. This is
still in place and is displayed when the default of 3600 is removed
manually.
https://www.pivotaltracker.com/story/show/167510474
> Set a hard default value on access token validity

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Parser/OidcClientIdParser.php
- src/Surfnet/ServiceProviderDashboard/Application/Parser/OidcngClientIdParser.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityOidcConfirmation.php
- tests/unit/Application/Parser/OidcClientIdParserTest.php
- tests/unit/Application/Parser/OidcngClientIdParserTest.php
The Oidc and Oidc TNG entities have different client id conventions. The parsers should ensure we always create the correct client id. Where currently the conversion logic is implemented in different classes, this solution enables the reuse of the conversion logic.
Both the Oidc and Oidc TNG classes, using or displaying the ClientID now use the correct parser to do so.
See: https://www.pivotaltracker.com/story/show/167510409
> Correctly display ClientID values

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/ResetOidcSecretCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/OidcGrantType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/EntityTypeFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ProtocolChoiceFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/UniqueRedirectUrlsValidator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/DeleteEntityClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/OidcngResourceServerClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Protocol.php
- tests/integration/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandlerTest.php
- tests/integration/Application/ViewObject/EntityActionsTest.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
- tests/unit/Infrastructure/DashboardBundle/Factory/EntityTypeFactoryTest.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
Warning: Another big one. Sorry about that!
This PR adds the OIDC TNG Resource Server entity type to SP Dashboard. From an SP dashboard standpoint, it is a thinned down version of a regular OIDC TNG client entity. The most notable change is that no ARP attributes can be configured for these entities. Other details like the redirect URLs, playground options, entity URLs (application/eula/logo/..) are not available. The differences between the entity types made me choose to create a completely new type implementation instead of an integration in the existing OIDC TNG entity.
I'd like this to be code and functionally reviewed. I tried my best to make the commit history in a reviewer friendly manner.
More details, and some back and forth between @quartje and me can be found on the Pivotal …
> Implement OIDC TNG resource server support

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
Saving drafts will be deprecated in the near future. The OIDC TNG
Resource Server will be the first entity type where this is not allowed.
> Only allow publication of OIDC RS entities

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Contact.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ContactList.php
- tests/unit/Infrastructure/Manage/Dto/ManageEntityTest.php
- tests/unit/Infrastructure/Manage/Dto/fixture/saml20_sp_contacts_response.json
The ContactType can be empty when fetching an entity from manage.
https://www.pivotaltracker.com/story/show/166232238
> Allow empty contact type on the contact information from Manage

- app/scss/components/flash.scss
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
- tests/integration/Application/CommandHandler/Entity/PublishEntityTestCommandHandlerTest.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
The scope of the story was narrowed down to just displaying a flash message, instead of rendering a full blown modal window. The clients are no longer displayed on the flash message, as the list view shows them.
https://www.pivotaltracker.com/story/show/168379274
> Show flash message after publishing new OIDC TNG resource server

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
On draft entities without a nameidformat, the subject type is now set with the default value (transient). This behaviour is already enforced on the save command, but that did not cover the possibility of existing draft entites without a nameidformat.
See: https://www.pivotaltracker.com/story/show/168533578
> Ensure the OIDC subject type is set

- app/scss/components/flash.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Twig/WysiwygExtension.php
The request (flash message) to select one or more resource servers to
introspect the relying party has been made more verbose.
1. The card border top color has been made green
2. A warning icon was added to the 'only access_tokens..' text
As requested in:
https://github.com/SURFnet/sp-dashboard/pull/306#pullrequestreview-287255417
> Make RP/RS connection request more verbose

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/PublishEntityTestCommandHandlerTest.php
- tests/webtests/EntityCreateOidcTest.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
- tests/webtests/EntityCreateOidcngTest.php
- tests/webtests/EntityCreateSamlTest.php
- tests/webtests/EntityPublishToTestTest.php
The IdP ACL data would be overwritten when a published manage entity was edited. This was the case because the data was still present on the entity (with the default allow all settings) and the entity is used to build the Manage Merge Metadata on.
The solution is to load the manage entity prior to publishing it, and loading the required ACL data on the Entity (that the JSON is based on).
https://www.pivotaltracker.com/story/show/168800119
Alternative to: https://github.com/SURFnet/sp-dashboard/pull/313
> Persist ACL data on entity edit publication

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
- tests/unit/Infrastructure/Manage/Client/QueryClientTest.php
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_oidc1.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_oidc2.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_oidc3.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_saml1.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_saml2.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/search_oidc.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/search_saml.json
- tests/webtests/EntityListTest.php
The += solution overwrites previously added keys with the ones found in
the array that is added.
The fix is to use array_merge
https://www.pivotaltracker.com/story/show/168834919
> Use array merge to prevent overwriting array keys

- .travis.yml
- CHANGELOG.md
- composer.json
- composer.lock
This change will apply the countermeasures to harden against
CVE 2019-3465 and will effectively bump `robrichards/xmlseclibs` to
version 3.0.4.
Travis will fail because the source branch is WIP. I however want to
merge this back to make sure that any further work will continue
with a secure sml2 version.
@MKodde please reset your local `feature/php72-support` branch
to make sure the changes land in your local branch before force-
pushing.
> Upgrade Stepup-saml-bundle to version 4.1.8

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
Previously the array merge function JsonGenerator:242 would try to merge
an undefined variable as the generateCertDataMetadata would not return
an array. This was already fixed on the previous PR in commit 4f320119.
A test was added to verify that this behaviour can not return in the
codebase.
Additionally, a `+=` operator has been changed out for an array_merge
function on line 255. This to prevent issues when the generateLogoMetadata
returns an empty array (would yield a fatal error).
> Allow empty certificate

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/TwigExtension/service_switcher.html.twig
When no services are present yet, the form view would yield a 500 error as no services are present yet to build the view with.
Making rendering conditional based on the presence of the 'selected_service_id' should remedy this issue
> Render service switcher when services present

- package.json
- yarn.lock
To prevent jquery plugins from being registred on the wrong jquery. This was happening. Parsley was not available on the Jquery distributed by Webpack Encore. Resulting in vague error messages.
> Resolve jquery at version 3.5.0

- src/Surfnet/ServiceProviderDashboard/Application/Dto/MetadataConversionDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/GeneratorInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/MetadataGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/SpDashboardMetadataGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGeneratorStrategy.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
- tests/unit/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGeneratorTest.php
- tests/unit/Application/Metadata/JsonGenerator/SpDashboardMetadataGeneratorTest.php
- tests/unit/Application/Metadata/JsonGeneratorStrategyTest.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
- tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
Arp attributes not tracked in the SPD forms where overridden. This PR takes care of this by changing the way attributes are filtered.
Most notable is the use of the Manage entity that is now used in the metadata generators.
https://www.pivotaltracker.com/story/show/170868465
> Prevent overriding of attributes

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/MetadataConversionDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityResetSecretController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Service/MangeQueryService.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidatorTest.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Infrastructure/Manage/Dto/ManageEntityTest.php
- tests/unit/Infrastructure/Manage/Dto/fixture/saml20_sp_response_not_excluded_from_push.json
- tests/unit/Infrastructure/Manage/Service/ManageQueryServiceTest.php
The main purpose of this PR is to ensure we do not override the exclude from push setting in Manage once an entity is included for push in production mode.
In addition, related files that where touched during investigation have been cleaned up.
Finally boyscout work was done, and a ManageQueryService was introduced. This service is not implemented thorugout yet, but is used to prevent the double injection of the manage test/prod query clients.
> Prevent overriding the 'exclude_from_push' attribute

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidator.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidatorTest.php
The OIDC TNG entities where checked with the protocol, but they are not known in Manage with the added protocol. The proto is removed using the parser that was added some time ago.
See: https://www.pivotaltracker.com/story/show/171439268
> Check ClientID existence without protocol

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
The arp motivation would be overwritten when a arp motivations was set in manage for one of the attributes not managed in SPD. This is solved  by checking for the presence of an attribute motivation. If there is a non empty value, it is loaded on the attrbibute. Preventing overwriting
that specific attr. motivation. 
**Merge targets:**
- `develop`
- `release/2.5`
See: [Pivoal reject message](https://www.pivotaltracker.com/story/show/170868465/comments/214384755)
> Prevent overwriting of ARP motivations

- src/Surfnet/ServiceProviderDashboard/Application/Dto/MetadataConversionDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
When scopes are configured in Manage, SPD would overwrite them with the hardcoded 'openid' setting. This is prevented by using the Manage configured setting when an existing manage entity is edited (re-published).
**Merge targets**
- Develop
- Release 2.5
https://www.pivotaltracker.com/story/show/170868465/comments/214384755
> Reuse scope attribute, preventing overwriting them

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailContactField.html.twig
- tests/webtests/EntityDetailTest.php
This balloon was previously situated on the top right. They are now
displayed nest to the first name attribute value.
https://www.pivotaltracker.com/story/show/172048805
> Reposition the contact information popup balloon

- app/Resources/views/form/fields.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
The enable playground and redirect URI tippies where missing. These are added in this PR.
https://www.pivotaltracker.com/story/show/169340980
> Set missing information balloons

- ansible/roles/spdashboard/defaults/main.yml
- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
The reporter and assignee are not required. And hence are removed from
the IssueFieldFactory and the config it is based on.
See: https://www.pivotaltracker.com/story/show/167024021
> Remove assignee and reporter from Jira config

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Coin.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
Only preserve the exclude from push flag when a client secret reset is performed. In all other cases, the flag is reset to be excluded from push
**Merge targets**
- release/2.5
- develop
https://www.pivotaltracker.com/story/show/171313433/comments/214387155
> Only preserve the exclude-from-push flag on client secret reset

- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Secret.php
- tests/unit/Domain/ValueObject/SecretTest.php
The special characters have been removed from the client secret generator. And uppercase characters have been added to the list of allowed characters. The list of required chars (which where the special chars) have been removed. Making the constructor slightly less complex.
https://www.pivotaltracker.com/story/show/170892653
> Make secret generator url encode safe

- .travis.yml
- src/Surfnet/ServiceProviderDashboard/Application/Dto/MetadataConversionDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
When resetting a client secret on production and the exclude from push attribute is missing, this indicates we are dealing with a published attribute. As the service desk not unchecks the coin checkbox, but simply removes it.
This additional logic covers that (understandable) 'misbehavior' of that coin.
Merge targets:
- `release/2.5`
- `develop`
https://www.pivotaltracker.com/story/show/171313433/comments/214527925
> Interpret missing exclude from push correctly

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/PushMetadataCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PushMetadataCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/UpdateEntityAclCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityAclController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityResetSecretController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidator.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Service/ManagePublishService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Service/ManageQueryService.php
- tests/integration/Application/CommandHandler/Entity/PublishEntityTestCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Entity/PushMetadataCommandHandlerTest.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidatorTest.php
- tests/unit/Infrastructure/Manage/Service/ManagePublishServiceTest.php
- tests/unit/Infrastructure/Manage/Service/ManageQueryServiceTest.php
This PR issues a metadata push after a production OIDC client secret reset action.
In order to make this possible I extracted the push logic from the existing publication command handlers. So some refactoring was required to get this task done. The first 5 commits cover the refactoring. And the final commit actually performs the metadata push after the secret reset.
__Warning:__
When functional testing this you will not actually be able to push the metadata from Manage prod to EngineBlock and the OIDCng proxy. The push will fail in Manage halfway. Metadata will have been pushed to Engine, but not to the not existing OIDC server. 
To fix your EngineBlock config after this task run:
`ANSIBLE_TAGS=vm_only_provision_manage_eb vagrant provision` …
> Push metadata on production secret reset

- CHANGELOG.md
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
The source and value parts of ARP attributes where overidden to their
defaults even when set in Manage.
See: https://www.pivotaltracker.com/story/show/173030675
> Do not overwrite source & value if set in Manage

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityOidcConfirmation.php
The OING TNG variaty was parsed correctly, but the resource server flavour was not parsed correctly showing the @ sign in the client id field where the entire protocol should have been removed.
https://www.pivotaltracker.com/story/show/169390094
> Parse OIDCng clientID correctly on secret modal

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
When opening an oidccng entity, the ARP attributes are listed at the
bottom of the view. Here we also rendered the EPTI (edu person targetted
ID) used to transport the NameId. This is an internal attribute that
should not be displayed to the end user.
https://www.pivotaltracker.com/story/show/169916839
> Stop showing EPTI on detail views

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Privacy/form.html.twig
The entry should be a valid url. By enabling parsely validation on the privacy questions form this goal could be achieved. All other fields needed updated 'required' attributes to prevent them from becoming
required form fields according to Parsley.
https://www.pivotaltracker.com/story/show/169895852
> Validate the privacyPolicyUrl field

- app/scss/excludes/forms.scss
- app/scss/pages/service_edit.scss
Previously they where all uppercased. By request, casing was changed to `normal`. 
Buttons and other UI elements are still uppercased. This was not part of the story to address those. Personally I like them uppercased to stand out a bit more.
https://www.pivotaltracker.com/story/show/169284607
> Make form labels normal casing

- ansible/roles/spdashboard/tasks/spdashboardvm.yml
This is needed because this is removed from Deploy to
be always installed.
> Add composer to Ansible for installation

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/PublishEntityProductionAfterClientResetCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/PublishProductionCommandInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityResetSecretController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
When resetting the client secret, no need to create a new publication
request to the service desk Jira. The item probably is already
published. Adding the ticket twice is not expected behaviour.
https://www.pivotaltracker.com/story/show/173220529
> Prevent Jira ticket on prod client secret reset

- app/DoctrineMigrations/Version20200623063105.php
- app/js/components/mock/service_create_form.html
- app/js/components/mock/service_edit_form.html
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
- tests/webtests/ServiceCreateTest.php
First commit: The institution guid field is removed. This is redundant as the CRM ID is actually the Institution GUID. The story merely stated which manage fields should be filled with the form values already present (in this case the coin:institution_id with the crm id)
Second commit: The insittution fields are saved to Manage.
See: https://www.pivotaltracker.com/story/show/163754504/comments/215468187
See: https://github.com/SURFnet/sp-dashboard/pull/362
> Finish Service changes started in #362

- ansible/roles/spdashboard/templates/spdashboard.conf.j2
- app/config/security.yml
- app/js/components/service_status.ts
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
Remove unwanted CSP settings that where explicitly added for the translations section of SPD. They are now overloaded in the Apache config. As Nelmio does not provide a means to override CSP config per page/path.
To get this into an existing dev-env. Please update the contents of your `/etc/httpd/conf.d/spdashboard.conf` with the contents of the Jinja template found in this PR.
https://www.pivotaltracker.com/story/show/173371989
> Increase CSP strictness

- app/scss/components/form.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
Using the style attribute is not allowed given the current CSP rules. Without this change the `default` submit button would show on the SAML form. This is required to trigger the default (save) action when pressing enter on the form.
https://www.pivotaltracker.com/story/show/173487094
> Prevent use of inline-style as this causes a CSP warning

- app/js/components/validation.js
- app/js/components/validator_helper.test.ts
- app/js/components/validator_helper.ts
- package.json
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/ValidRedirectUrlValidator.php
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/ValidRedirectUrlValidatorTest.php
- yarn.lock
The Jest test behaves differently to the browser when it comes to the `flipProtocol` method. The URL parser is able to correctly parse on the Jest test, but fails to do so in a Firefox browser.
@pablothedude any thoughts on this?
For example, try this redirect url `spdashboard.dev.support.surfconext.nl://https/my/path`
**Edit**
@pablothedude suggested to use `parse-url` library. And that fixed the problem with ease.
See:
`https://www.pivotaltracker.com/story/show/172833472`
> Enable and fix Url validation

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/AttributesMetadataRepository.php
- src/Surfnet/ServiceProviderDashboard/Legacy/Repository/AttributesMetadataRepository.php
When removing SP-Dashboard attributes they were merged back
with the values known in Manage. This prevented the removal of
attributes in SP-Dashboard.
https://www.pivotaltracker.com/n/projects/1400064/stories/173508616
> Merge manage attributes only

- app/Resources/metadata/attributes.json
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
- tests/unit/Legacy/Repository/AttributesMetadataRepositoryTest.php
The memberOf attribute was defined as attribute but didn't seem to be
managed by SPD. So when pushing the attribute to Manage it was replaced
with an empty value. So therefore the attribute was removed and a
couple of checks for mapping values to getters/setters could be
removed to make the code more explicit and thus better readable.
https://www.pivotaltracker.com/n/projects/1400064/stories/173508616
> Remove memberOf as managed attribute

- ansible/roles/spdashboard/templates/parameters.yml.j2
- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
The distinction between the oidc and oidcng entites was removed once we dropped oidc (old style) support. Keeping the one most descriptive (without the NG suffix) was most logical.
https://www.pivotaltracker.com/story/show/175288814
> Deprovision the oidcng playtround uris

- docker/httpd/conf/000-default.conf
With this change, the translations work again
> Docker: Add content security policy to the docker httpd config

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
In order to test for the correct (configured) ticket type in the entity
service, we need the configured types in the service. Previously these
where hardcoded. But this did not work in an evn where the configuration
was set differently..
See: https://www.pivotaltracker.com/story/show/175288951
> Inject Jira ticket types in EntityService

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
This is no longer required as the actual entity status is reflected on
the manage entity. Using Jira for this purpose leads to incorrect entity
status in SPD
> Stop matching the Jira status to the entity status

- composer.json
- composer.lock
During @quartje's Docker adventures he noted that the required php extensions are not explicitly required in the Composer config. 
This PR adds the required extensions to composer.json
https://www.pivotaltracker.com/story/show/173356684
> Register required php extensions in composer.json

- app/DoctrineMigrations/Version20210211124755.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveEntityCommandInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveSamlEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/integration/Application/CommandHandler/Entity/SaveOidcngEntityCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Entity/SaveOidcngResourceServerEntityCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
- tests/unit/Application/Service/EntityMergeServiceTest.php
- tests/webtests/EditServiceTest.php
- tests/webtests/ServiceCreateTest.php
The organization display, and the regular organization names are now manageble via the Service create and edit forms.
Whenever an entity of the service is saved, the current values of the service's org names are transported to the manage entity.
@quartje is investigating if the Organization URL should also be made configurable in the Service create/edit views. If that task is to be performed. That should land in a new PR, this PR can be used as a template for the tasks that need to be performed.
**Warning**: A database migration is required to test this feature
**See**: https://www.pivotaltracker.com/story/show/175513094
> Manage organization names

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
This id ensures we know which of the services was selected to create a new
entity fom.
https://www.pivotaltracker.com/story/show/176976523
> Ensure presence of InputId on new entity form

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/unit/Application/Metadata/fixture/oidc10_rp_response.json
Stop setting default scope oidc on RP entities. This is no longer required, as the resource servers are migrating to their own entity type.
https://www.pivotaltracker.com/story/show/176961848
> Remove default scope from Oidcng RP entities

- tests/unit/Application/Metadata/JsonGeneratorStrategyTest.php
- tests/unit/Application/ViewObject/EntityTest.php
- tests/unit/Domain/Entity/Entity/ProtocolTest.php
Some test oidc remaining support was removed. In a previous commit the
OIDC client id generator was removed. This can be seen as part of the
task mentioned below.
https://www.pivotaltracker.com/story/show/175139821
> Remove remaining OIDC crud

- package.json
- yarn.lock
Multiple JQ versions means trouble in the land of JS. Webpack does not
know which to use. And are used in conjunction, causing the one to have
a certain library and the oterh version not.
Pinning to the newest JQuery version seemed to fix the issue.
https://www.pivotaltracker.com/story/show/176979397
> Repair ParsleyJs by pinning JQ versions installed

- docker/Dockerfile
- docker/conf/zz-docker.conf
The zz-docker.conf in the local directory overwrites the default file as
supplied in the Docker image. This allows us to set the secure flag on
the session cookie, and set other php ini settings if needed
> Docker: Add php-fpm override config

- app/js/components/service_add_entity.ts
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Prior to this change, the template option did not always have a default choice.
This change ensures there is always a checked option for the template.
See the story in pivotal for more info: https://www.pivotaltracker.com/story/show/165599582
> Ensure template has default choice

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/EntityTypeFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactoryInterface.php
Prior to this change, when copying a oicdng or oicdng-rs entity, the id was not editable.
This change adds a check to see whether or not the edit form is due to a copy action.  If it is a copy action, the id field is editable.  Else it is not.
See the story in pivotal for more info: https://www.pivotaltracker.com/story/show/165599582
> Ensure copy ClientId is editable

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Constants.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Protocol.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/QueryEntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Http/HttpClient.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
- tests/unit/Application/Metadata/fixture/oauth20_rs_response.json
- tests/unit/Infrastructure/DashboardBundle/Factory/EntityTypeFactoryTest.php
- tests/unit/Infrastructure/Manage/Client/QueryClientTest.php
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/read_response_oauth.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/search_oauth.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/search_oidc.json
- tests/unit/Infrastructure/Manage/Client/fixture/search_result_overwrite_bug/search_saml.json
- tests/unit/Infrastructure/Manage/Dto/ProtocolTest.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
- tests/webtests/Manage/Client/FakeQueryClient.php
This updates SPDashboard to work with the new Manage enitty type: oauth20_rs. The previous piggy back strategy to register these entities on the oidc10_rp type is no longer required. More info in the story: https://www.pivotaltracker.com/story/show/176961821
Only the last commit of this PR needs to be reviewed. Before merging. This PR must be rebased onto develop. To functionally test this. The new Docker Dev env should be used. This should be as simple as running `docker-compose up`.
> Use `oauth20_rs` Manage entity scheme for resource servers

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
Prior to this change, the typecheck for the redirect url failed when the redirect url wasn't set.
This change ensures the check doesn't fail by ensuring that if the field isn't set an empty array is used.
Bug found while testing PR #413
> Ensure typecheck for redirect url doesn't fail

- Vagrantfile
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcClientInterface.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngResourceServerClient.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Grants.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/webtests/EntityCreateOidcngTest.php
In order to support setting multiple grants, several changes to the code where required.
1. Support for multiple grants in SPD is required. Previously we only handled a single grant. This is now a simple collection of grants
2. Do not overwrite the Manage managed grants. These are being ovewritten as we only kept a single value and posted that back into the manage environment.
Note to reviewer: 
~This was rebased onto the docker PR. Please only review the `Allow setting multiple grants` commit.~
The additional commit was a fixup of a mistake I made. One of the previous stories mentioned that OIDCng entities should not track scopes at all. This was not implemented fully yet.
See: https://www.pivotaltracker.com/story/show/174746007
> Allow setting multiple grants

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Attribute.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AttributeList.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
- tests/unit/Domain/Entity/Entity/AttributeListTest.php
These where previously reset on a publication to manage. This resulted in loss of data on Manage side. By tracking the manage data and only updating the motivations, this problem is solved.
https://www.pivotaltracker.com/story/show/174549876
> Support attributes with multiple values

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcClientInterface.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngResourceServerClient.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/QueryEntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
- tests/webtests/Manage/Client/FakeQueryClient.php
This one's a doozy. The PR is twofold.
1. Allow read-only view of RS outside of team
The detail window of RP enitties now also show RP's from outside their own team. This is possible as there is no team restriction in Manage.
2. Prevent RS overwrites when outside of team 
SPD would overwrite these changes upon push to manage. That is also fixed in this PR.
More details: https://www.pivotaltracker.com/story/show/173371940
> Allow Resource Servers from outside of RP's team

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AttributeList.php
A missing attribute value will cause the system to break. Setting the default (a star) fixes this problem. This is implemented in the attribute generator.
In addition the Attribute list is now also dealing with new attributes correctly. It would previously only deal with existing attributes.
Relates to:
- https://www.pivotaltracker.com/story/show/174549876
- https://github.com/SURFnet/sp-dashboard/pull/413
> Ensure attribute value is set on publishing entity

- app/scss/components/modal_add_entity.scss
- app/scss/components/tooltip.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Prior to this change, the create entity modal had no extra info to explain the different fields / titles.
This change ensures that protocol gains an explanation link & template gains an explanation fold-out (aka tooltip modern version).
For more info see https://www.pivotaltracker.com/story/show/165599582
> Add info fields to create entity titles

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Prior to this change, when a user tried to copy an entity and it went wrong: the redirect url was to the admin service overview.  This obviously led to an "access denied".
This change ensures that the redirect url is dependant on the user's access level.  Users get redirect to the service overview, admins to the admin service overview.
For more info see https://www.pivotaltracker.com/story/show/165965607
> Ensure redirect url is correct for copy action

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Issue.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
- tests/unit/Domain/ValueObject/IssueCollectionTest.php
When service desk closes or resolves a Jira tikcet, but the matching
entity is still present in Manage, we should no longer consider it as
a request for delete status code.
https://www.pivotaltracker.com/story/show/176244612
> Consider closed and resolved status from Jira

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AttributeList.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
It was believed the manage attributes where no longer overwritten. This was not the case. As the new logic does not actually check if the attribute is either manage or spd tracked. This is now fixed in the Json generator. Here we can use the attribute dictionary (repo) to get an intersection of the spd and manage managed attributes.
> Refrain from overwriting Manage tracked attributes

- .github/workflows/main.yml
I'd like to be able to test the develop branch on a regular basis, but so far, only on release or on a commit in a pull_request a docker image was built. Now on all commits in the develop branch a docker image will be built
> Build docker image when merging to develop.

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
Manage identifies a resource server as type: oauth20-rs and not oauth20_rs
> Resource server: Fix the type as set in manage

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
Prior to this change, the tooltip in the add test entity modal was not clickable ("what does this mean").
This change ensures that it is by adding a unique id.
> Make tooltip for test entity clickable

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
Prior to this change, admins could not see the "new production entity" link.  Added to that when the label text was semi-long the hover effect was a tad ugly.
This change ensures that admins can see the link & that the hover effect is ok for a longer label.
> Show new production entity link for admins

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Without resetting the manage id, the action would result in an entity update action.
> Ensure entity copy results in a new entity

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Prior to this change, the form was sometimes evaluated as not submitted when it was ($form->isSubmitted() yielding the wrong result).  This resulted in an unstyled form for the modal on a blank page.
This change ensures that when the modal is "posted" (aka submitted), it'll be considered submitted & thus be redirected to the right page.
> Ensure modal redirects correctly when submitted

- app/js/components/validator_helper.test.ts
- app/js/components/validator_helper.ts
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/ValidRedirectUrlValidator.php
Prior to this change, custom urls didn't validate correctly.
This change ensures that custom redirect urls are valid.  Custom urls are urls where the hostname is provided in reverse as per https://tools.ietf.org/html/rfc8252#section-7.1.
We also allowed for technically "faulty" custom redirect urls which feature a double //.  Eg: nl.test://redirect.  This ought to be nl.test:/redirect as per te specs (with a single /).  The use case where a user types it with double slash is covered however.
For more info see https://www.pivotaltracker.com/story/show/173624681
> Fix custom redirect url validation

- app/scss/components/tooltip.scss
Prior to this change, the content of the tooltip was visually hidden but still used up room.
This change ensures that when the tooltip is hidden the content is as well
> Hide content of tooltip

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityModal/addEntityModal.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
Prior to this change, the validation would always throw an error for the create entity modal when submitting a test entity.  This is because if the form is not "submitted" it is considered invalid.
This change alters the validation to check whether there are actual form errors.  If none are found the form is considered valid.
Following the boyscout rule the ids for the titles were also made unique to the modal so they pass html validation.
**Edit @MKodde**
The solution to this problem is somewhat controversial, and can be considered bad practice. We created a TD ticket to later fix this issue. https://www.pivotaltracker.com/story/show/177183585
> Remove form validation from CreateNewEntityType form

- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
The RS entities can be viewed from outside of the users team. This is a requirement.  But it was not allowed for production entities.
In addition two boy scout rule actions have been undertaken:
1. The test entities are now testing for explicit access to the other entity types (was only performed for prod entities)
2. Typehints where added to the method that was touched in this PR
> Do not verify service restraint on RS entities

- app/config/parameters.yml.dist
- docker/Dockerfiledev
- docker/conf/xdebug.ini
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
The revision note was lost in the publication action when updating an existing entity.
This PR also addresses the incorrect Xdebug setup as we now get Xdebug3 vs 2.
> Merge comment (revision note) upon updating entity

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
The check for the privacy questions enabled feature flag (service edit / create form) was not evaluated while rendering the privacy questions nag banner.
Note that this PR is based on the #435 PR. Only the last commit is relevant for this bugfix.
As described in bug report: https://www.pivotaltracker.com/story/show/177677377
> Only show the privacy questions banner when toggle is on

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Coin.php
- tests/unit/Domain/Entity/Entity/CoinTest.php
The exclude from push is set on the manage prod entity. And it was not
merged correctly onto the updated (SPD) entity that is to be published
to manage. This fixes that issue for the Coin value object.
https://www.pivotaltracker.com/story/show/177659443
> Ensure exclude from push coin value is honored

- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Issue.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
Previously the status was added to the Jira Issue solution. This status is used to figure out the entity status.
Problem is that the status id was not yanked from the Jira status field, the entire status object was set on the type restricted Issue constructor.
While at it, a similar development issue was fixed.
https://www.pivotaltracker.com/story/show/177659652
> Repair faulty Jira ticket status implementation

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
Prior to this change, production entities could not be added because the link was not clickable in all situations.
This change ensures the link is always clickable.
Pivotal issue at: https://www.pivotaltracker.com/story/show/177677810
> Ensure add production entity is always clickable

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
Prior to this change, an empty attributes array got converted to an empty JSON array (makes sense).  However, when not empty the array got converted to a JSON object (as at that point it was an associative array before conversion).  The JSON schema for ARP specifies that the attributes property is an object, so the empty array did not get through schema validation.
This change replaces any empty attributes-array by a simple PHP stdClass (empty).  Which does get converted to an empty object in JSON.
Pivotal story at https://www.pivotaltracker.com/story/show/177697851
> Ensure ARP attributes is an object when empty

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
- tests/webtests/ServiceOverviewTest.php
Prior to this change, the privacy link was only visible to admin users.  Meaning that once the questions were answered, you could no longer go to the privacy questions.
This change ensures the link is now also visible for normal users (as was the original intent).  Additionally it also adds a link to the privacy questions in the tooltip for the status summary.
Pivotal ticket at https://www.pivotaltracker.com/story/show/177682438
> Ensure privacy link is visible for normal users

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/ResetOidcSecretCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Organization.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityResetSecretController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
The Organization value object is loaded from the manage provided metadata. This metadata might or might not include the Organization Name (NL/EN). We track the organization name on the Service entity. And that name is leading in the entities organization names. To ensure we have those org names on every Entity Manage interaction. I now update the OrgNames based on the service entity value. 
This happens to fix the issue where the client secret reset would fail on a missing org name value.
Bugfix for bug reported in: https://www.pivotaltracker.com/story/show/177701148
> Client secret reset service issue

- docker/Dockerfiledev
- docker/conf/prep_oc.sh
This PR makes sure the latest openconext docker image is pulled.
Some changes were necessary to change to the new Haproxy configuration layout
> Use the lastest OpenConext docker image

- docker/conf/000-default.conf
- docker/conf/httpd.conf
This adds cache headers for the production Apache docker image.
> HTTPD: Add cache headers

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/AllowedIdentityProviders.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
Prior to this change, an entity based on a template would keep the ACL from the original entity.  This obviously should not be the case, as it's a new entity with it's own ACL.
This change ensures the new entity receives a fresh ACL.
Pivotal story available at: https://www.pivotaltracker.com/story/show/177884116
> Ensure that copied entities have a clear ACL

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
Prior to this change, four attributes weren't shown: organization attribute, organization type attribute, personal code attribute and edu person targeted id attribute.  These attributes were visible in the edit and create actions though.
This change adds the correct urn-lookups for the organization attribute, the organization type attribute and the personal code attribute thereby rendering them visible.  It also adds the edu person targeted id attribute to the detail view and to the entitydetail object.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/177945756
> Ensure all attributes are shown on view

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
Prior to this change, leaving an arp motivation empty was possible on test, but not on production.  However, an attribute with an empty motivation was not added to the ARP.  Whilst privacyfriendly, this didn't match the expectations.
This change uses the same validation for production as for test when it comes to attributes.  Given that production and test now have the same behaviour things should be clearer.
Pivotal story: https://www.pivotaltracker.com/story/show/177774124
> Ensure attributes are validated also on test

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
Prior to this change the organizationNameEn and -NL fields were removed from the SaveSamlEntityCommand in commit 45864bd66c8c027998a54f00615fea66bc033715.  However, the LoadMetadataCommandHandler still had them as part of the mapTextfields method.  This caused numerous error logs.
This change removes the leftover, and thereby will clear the logs of the error.
For the error logs and pivotal ticket see: https://www.pivotaltracker.com/story/show/177742668
> Remove organizationName leftover

- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/IssueCollection.php
- tests/unit/Domain/ValueObject/IssueCollectionTest.php
By setting the default value of the issues collection to be an array.
Count function can be used safely without warning. As calling count on
null started yielding warnings in PHP7.
Resolves first warning of:
https://www.pivotaltracker.com/story/show/177742668
> Prevent calling count on null

- docs/index.md
- docs/release.md
Prior to this change there was no documentation concerning the release procedure.
This change adds that documentation.
> Add release documentation to dev docs

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
Prior to this change, the description for NL was shown under EN and vice versa.
This change shows the correct description per language
Pivotal ticket at: https://www.pivotaltracker.com/story/show/178121329
> Show the correct descriptions per language

- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
- tests/integration/Application/ViewObject/EntityActionsTest.php
Prior to this change, the edit option was visible for entities that had the status of removal requested.  Upon clicking the edit button, an access denied screen was shown.  This behaviour was right, but the option to click edit should not be present.
This change removes the edit option.
Pivotal ticket: https://www.pivotaltracker.com/story/show/178034009
> Hide edit for PE on removal requested

- package.json
- yarn.lock
Two Jquery versions cause problems when Webpack encore serves off Jquery
to the javascript. Pinning Jquery to the known working JQ version solves
that issue.
https://www.pivotaltracker.com/story/show/178316980
> Prevent double JQuery installations

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OauthClientCredentialEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
Prior to this change the names of the organization were not mandatory.
This change makes them mandatory.
Pivotal story at: https://www.pivotaltracker.com/story/show/177659336
> Ensure name in En/Nl is mandatory

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
Prior to this change, users who deleted a published entity were redirected to /service/{id}, for which one needs admin access.  This resulted in an error.
This change ensures that the redirection takes into account their access level.  Normal users are now redirected to '/', admin users see no change.
Pivotal ticket: https://www.pivotaltracker.com/story/show/178034022
> Fix user redirect after deleting published entity

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/oidcConfirmationModal.html.twig
Prior to this PR there was only one message for both environments to which a OIDC was published.
This PR ensures that a separate message is possible, depending on the environment.  In all other respects the modal remains the same.
It also applies the boyscout rule to fix a broken translation.
Pivotal ticket at https://www.pivotaltracker.com/story/show/175656934
> Separate modal oidc for environment

- app/Resources/views/base.html.twig
- app/config/routing.yml
- app/config/security.yml
Prior to this change, there was no logout & the redirect did not work.
This change adds the logout behaviour & redirects to the url as specified by the user.
Pivotal story @ https://www.pivotaltracker.com/story/show/173125614
> Ensure logging out works & redirects

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
- tests/webtests/EntityCreateOidcngTest.php
Prior to this change, Client Ids and redirect url could be a mix of lowercase and uppercase.
This change lowercases the redirect urls and the client ids in the saveOidcNgEntity.  It also applies the boyscout rule and fixes an error when viewing the oidc entities.
No tests were added here as i did not find an existing test case.  But they will be added when the cypress ticket is implemented.
Pivotal ticket @: https://www.pivotaltracker.com/story/show/173276689
> Lowercase client ids and redirect url

- src/Surfnet/ServiceProviderDashboard/Application/Service/LoadEntityService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- tests/unit/Application/Service/LoadEntityServiceTest.php
Prior to this change, the entity id was not validated for uniqueness with SAML entities.  This lead to an indistinct error when publishing.
This change applies the correct validation for uniqueness.  This ensures the error is shown on the create page with a more helpful text.
It also employs the boyscout rule to use type hinting and to get rid of some legacy code.
Pivotal ticket @: https://www.pivotaltracker.com/story/show/172022288
> Validate entity id for SAML

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngClient.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/OidcngResourceServerClient.php
Prior to this change the entire redirect url was lowercased.  That wasn't the idea but not entirely clear in the orinal feature request.
This change lowercases only the correct parts.
See pivotal comment / ticket @ https://www.pivotaltracker.com/story/show/173276689/comments/225087260
> Lowercase protocol & hostname in redirect url

- docs/generator.md
- docs/index.md
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/UpdateEntityAclCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/GeneratorInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGeneratorStrategy.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OauthClientCredentialsClientJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/PublishEntityRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/webtests/Manage/Client/FakePublishEntityClient.php
Prior to this change, the entire metadata for the entity was sent to mange just to update the acl.  This lead to some subtle bugs because too much was updated.  The user only updates the acl, so we should not send more than that to manage.
This change limits the data sent to manage to the data pertinant to the acl change.
Pivotal ticket @ https://www.pivotaltracker.com/story/show/178461498
API info for manage @ https://github.com/OpenConext/OpenConext-manage/wiki/API#merge-write
> Only update acl fields on edit idp whitelist

- docker-compose.yml
- docker/Dockerfiledev
In order to use this, you need to recreate some parts of your dev env:
Delete the mongo database: 
```
docker volume rm sp-dashboard_spdashboard_mongo
```
Pull the new image:
```
docker pull ghcr.io/openconext/openconext-deploy/openconext-core:feature_build_image_with_teams_included
```
Rebuild the OpenConext container
```
docker-compose build openconext
```
Start it, wait some time until everything is started. Then you need to fix a scope provisioning issue in OpenConext deploy:
- navigate to https://manage.vm.openconext.org
- Open the scopes tab, and add the scope "groups" (name and description don't matter)
- Move to the resource servers tab, and edit the resource server voot.vm.openconext.org
- Remove the "groups" scope. And save it
- Reopen it, and add it again (yes this is really …
> Docker for development: Add Teams

- app/DoctrineMigrations/Version20211013095152.php
- app/config/config.yml
- app/config/services.yml
- docker-compose.yml
I've tried setting up session storage in the database, since I want to make the SPdashboard suitable for using in a multi node Docker setup, without having to worry about session affinity or saving session files during restarts. 
This setups works, and would even be nicer if we can reuse the Doctrine database settings. Is that possible in any way?
> Store the sessions in the database: Nice for HA setups

- docker/Dockerfiledev
- docker/conf/start.sh
so they're not deleted during a restart
> Docker: Move the startup scripts away from /tmp 

- docker-compose.yml
- docker/Dockerfile
- docker/Dockerfiledev
We build openconext containers in a seperate project, so they can be reused in other OpenConext projects
> Docker: use the prebuilt openconext containers

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Contact.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Handler/ProcessSamlAuthenticationHandler.php
While researching a reported issue by a user it was not clear which messages in the logs to look for. Log who authenticates so we can quickly find associated log lines with that session.
> Log authenticated user

- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- tests/unit/Application/Service/ServiceServiceTest.php
- tests/webtests/ServiceCreateTest.php
- tests/webtests/ServiceSwitcherTest.php
As an administrator, I sometimes want to be able to find a space when I know only the teamId. Add the most significant part of the teamId urn to the service switcher so you can find services also in that way.
> Add the teamId also to the service switcher

- app/js/components/delete_member.ts
- docs/teams.md
Work done in this pull request
- Fixed visual bug of removal of the wrong team member after deletion.
- Update teams.md to explain how to add members.
https://www.pivotaltracker.com/story/show/181418526
> Fix visual bug of removal of the wrong team member after deletion

- docker/Dockerfiledev
- docker/conf/xdebug.ini
Replacing the config file for xdebug makes xdebug no longer work. After this change, a docker-compose build should build a new fpm image with a working xdebug
> Docker: Fix xdebug

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
During a peer programming session with Bart, we encountered that the request delete of prod entity status was not reverted back when the issue status in Jira was set to 'resolved'. Resulting in the ticket retaining its faulty status. This feature was encountered when users unintentionally clicked the 'remove prod entity' button. And the support team verified the action with the user, resulting in the resolution of the ticket (without any action). This should have resulted in the entity status reverting back to 'published'.
By simply filtering the Jira results to only show the Unresolved items we resolved this issue. With the additional benefit of only retrieving the active tickets at that point. Decreasing the processing time and resource hogging.
See: …
> Retrieve only Unresolved issues from Jira

- .gitignore
- README.md
- docker-compose.override.yml.dist
- docker/conf/override/xdebug.override.ini
Modern macos docker implementations use a vm to run containers in. Nothing wrong with that. In order to use xdebug step debugging, the xdebug config needs some tweaking to get it working. By providing this docker compose override, we can adjust the setup in the php-fpm container without messing with the base images.
See: https://www.pivotaltracker.com/story/show/183285237
See: https://blog.jetbrains.com/phpstorm/2018/08/quickstart-with-docker-in-phpstorm/
> Provide host.docker.internal friendly xdebug setup

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- tests/webtests/ServiceSwitcherTest.php
As soon as you go to spdashboard you will come to the Service overview page. When you select a service and click on the logo the  selected service is cleared and allows you to select any service from the service switcher.
see: https://www.pivotaltracker.com/story/show/182233103
> Clear selected service on service switcher when serving sp dashboard

- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/EntityChangeRequestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/MailService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/TicketService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/MetaData.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/Compiler/IssueRepositoryCompilerPass.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandlerTest.php
- tests/webtests/EntityDeleteTest.php
A Jira ticket with a distinctive issue type is created. The actual issue type is yet to be determined, but can be set in the parameters.yml during deployment.
The title and description of the Ticket have been made translatable, a default was added to the default translations file.
See: https://www.pivotaltracker.com/story/show/182411800
See: https://www.pivotaltracker.com/story/show/179749372
> Create a Jira ticket after creating an entity change request

- app/scss/pages/change_request.scss
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDtoCollection.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDtoComparer.php
- src/Surfnet/ServiceProviderDashboard/Application/Exception/InvalidDateTimeException.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Contact.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityChangeRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/actionsForList.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/changeRequestAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/changeRequest.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/EntityChangeRequestClient.php
- tests/integration/Application/ViewObject/EntityActionsTest.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Domain/ValueObject/ChangeRequestDtoCollectionTest.php
- tests/unit/Domain/ValueObject/ChangeRequestDtoTest.php
- tests/webtests/EntityEditTest.php
- tests/webtests/Manage/Client/FakeEntityChangeRequestClient.php
- tests/webtests/fixtures/change-request/manage-change-request-with-note.json
Withing sp dashboard we want to make the  outstanding changes be transparent for a supplier. Therefor a new screen "Requested changes" can be selected from the context menu at an published entity. Each outstanding change contains the list of changes together with the date of creation and a possible note.
> Provide a change request overview

- app/config/parameters.yml.dist
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
The Reporter in Jira needs to be a known Jira user for the organisation that subscribes to Jira. In this case we fill it with a name/mail address of a Service contact person. And that person wil most probably not be known in Jira. Yielding a big fat error.
The solution is to use a custom field (that is already provisioned in the SURF Jira setup). That field is then filled with the Name/Email combination.
This goal was reached by following the existing pattern that was already in place for the ManageId and the EntityId custom fields.
A fixup for: https://github.com/SURFnet/sp-dashboard/pull/523 See https://www.pivotaltracker.com/story/show/179749372/comments/233715744
> Transform Jira reporter name to custom field

- app/config/attributes.json
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeNameService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeNameServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ValueObject/EntityMergeAttribute.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Constants.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/MetaData.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/AttributeTypeFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/AttributeRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Parser.php
- tests/integration/Legacy/Metadata/ParserTest.php
- tests/integration/Legacy/Metadata/fixture/attributes.json
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
- tests/unit/Application/Metadata/fixture/attributes.json
- tests/unit/Application/Service/EntityMergeServiceTest.php
- tests/unit/Application/Service/fixture/attributes.json
- tests/unit/Infrastructure/DashboardBundle/Dto/AttributeTypeInformationTest.php
The existing saml and oidc entity forms let loose their data into corresponding Command objects. These objects now also enumerate every possible Attribute.  Now these attributes are removed from the commands and replaces by an Attribute array which is loaded from the attributes.json config. 
The saml and oidc form use the magic setter and getter of the command objects. On their turn these magic getter and setter use a more readable and useful local setter and getter. Perhaps a more elegant solution is possible after migration of the project to version 5 or higher by using PropertyAccessors in the form, or the 'getter' and 'setter' features of the form builder. Ideally the magic getter and setter could possibly be removed.
Some simple validation is done on the attributes by using a …
> Manage the entity attributes commands

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/LoadMetadataCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Exception/AttributeNotFoundException.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Metadata.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Parser.php
- tests/integration/Legacy/Metadata/ParserTest.php
- tests/unit/Domain/ValueObject/MetadataTest.php
From a SAML url the $descriptor->AttributeConsumingService->RequestedAttribute the metadata and attributes can be loaded into the form. The metadata attributes are no longer hard coded and will use a getter and setter to get set its attributes. 
The attributeNameService provides the available names within the SPD system and is used to setup the metadata attributes requested values.
see: https://www.pivotaltracker.com/story/show/182220241 ### 4. LoadMetadataCommandHandler changes
> Load manage entity attributes using dynamic attributes

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
- tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php
Previously we would also show the reporter name on that field. But this field can only be a mail address
> Set only email on custom reporter Jira field

- app/scss/pages/change_request.scss
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDto.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDtoCollection.php
- src/Surfnet/ServiceProviderDashboard/Application/Dto/ChangeRequestDtoComparer.php
- src/Surfnet/ServiceProviderDashboard/Application/Exception/InvalidDateTimeException.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityChangeRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/actionsForList.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/changeRequestAction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/changeRequest.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/EntityChangeRequestClient.php
- tests/integration/Application/ViewObject/EntityActionsTest.php
- tests/unit/Domain/ValueObject/ChangeRequestDtoCollectionTest.php
- tests/unit/Domain/ValueObject/ChangeRequestDtoTest.php
- tests/webtests/EntityEditTest.php
- tests/webtests/Manage/Client/FakeEntityChangeRequestClient.php
- tests/webtests/fixtures/change-request/manage-change-request-with-note.json
This branch was previously under scrutiny in https://github.com/SURFnet/sp-dashboard/pull/525
That PR got merged into a branch that later ditched the change request overview changes. And that resulted in the feature not landing into `develop`.
This PR should set the record straight. No code changes where made, so this will be merged once the automated tests pass.
> Add a change request overview for production entities

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
All attribute related messages that are no longer used or moved to the attributes.json, due to the dynamic making of the attributes of the entities, have now been cleaned up.
see: https://www.pivotaltracker.com/story/show/182220241
> Clean up of attribute related messages

- app/Resources/schemas/attributes.scheme.json
- build.xml
- docs/arp-attribute-configuration.md
- docs/testing.md
- package.json
- yarn.lock
When attributes are maintained within the attributes.json some validation has to be done to avoid unwanted errors. An attributes.scheme.json has been added to check to attributes.json against this scheme. The initial version of the scheme is generated by https://extendsclass.com/json-schema-validator.html. Further refinement is done by adding so called 'patternProperties' to support multiple languages easily by extending the pattern "^en$" by e.g. "^en|nl$" to support Dutch. Another adjustment to mention is the enumeration of supported entityt ypes within the excludeOnEntityType property.
see: https://www.pivotaltracker.com/story/show/182219948
> Attribute schema validator

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
When a prod entity is saved (change request) sucesfully, we used to add a flash message. Showing the user the save action was a succes. This is no longer the case, as this action would result in showing a thank you page. And having both a flash message and a thank you page is a little too much.
See: https://www.pivotaltracker.com/story/show/182246029/comments/233754893
> Remove flash message from production edit action

- tests/webtests/EntityCreateOidcngTest.php
- tests/webtests/EntityCreateSamlTest.php
- tests/webtests/EntityEditTest.php
Some tests failed when attributes were removed from the attributes.json. This is now fixed to fetch the attributes from the attributes service and build up the form data for the attributes dynamically
> Test failure on removed attribute(s)

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
When finding Jira tickets by manage id and an issue type (when looking for a specific ticket for a specific entity). The `resolution` was not taken into account. Resulting in opening no new ticket when a ticket was previously resolved in Jira.
See: https://www.pivotaltracker.com/story/show/182411807/comments/233832245
> Filter out resolved Jira tickets

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/MetaData.php
- tests/unit/Domain/Entity/Entity/MetaDataTest.php
Not the actual acs uri was set on the array representation, but the field identifier. That resulted in the change request not registering any changes between entity revisions.
See: https://www.pivotaltracker.com/story/show/182411730/comments/233831779
> Set ACS location on MetaData array representation

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/EntityDiff.php
- tests/unit/Infrastructure/Manage/Dto/EntityDiffTest.php
When diffing entity changes, the grants and redirect urls must be included on the 'add all values' and not in a diff manner. I previously implemented this. But it was added to the diff also when no actual changes where applied to the data.
By only adding them when the diff result yielded a result. I worked around that problem.
The test shows the different combinations. And the expected outcomes. That should help in getting a better grasp of the correct behavior.
> Handle grants and redirect urls correctly when updating an OIDC entity

- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ChangeRequestServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Protocol.php
- src/Surfnet/ServiceProviderDashboard/Domain/Exception/ProtocolNotFoundException.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/EntityChangeRequestRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityChangeRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/changeRequest.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/EntityChangeRequestClient.php
- tests/unit/Domain/Entity/Entity/ProtocolTest.php
- tests/webtests/EntityEditTest.php
- tests/webtests/Manage/Client/FakeEntityChangeRequestClient.php
The protocol was hardcoded to saml_sp. Now the protocol used within the entity is used when requesting the changes from manage.
see: https://www.pivotaltracker.com/story/show/182411816
> Repair hardcoded saml change request to protocol within the entity

- app/scss/components/modal.scss
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/ResetOidcSecretCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailMonospacedTextField.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/oidcConfirmationModal.html.twig
- tests/integration/Application/CommandHandler/Entity/ResetOidcSecretCommandHandlerTest.php
- tests/webtests/EntityCreateClientCredentialsClientTest.php
- tests/webtests/EntityCreateOidcngResourceServerTest.php
1. The push action in manage is now triggered not only for production entities, but also for the ones on test. See: https://www.pivotaltracker.com/story/show/183572242
2. The secret that shal be only displayed once. Is reformatted slightly different (monospaced) allowing for easier reading of similar looking
characters. See: https://www.pivotaltracker.com/story/show/182408063
> Improve secret reset behavior

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/MetaData.php
- tests/unit/Domain/Entity/Entity/MetaDataTest.php
- tests/unit/Domain/Entity/Entity/fixture/read_response_same_acs_location_different_binding.json
We only support this binding in SURFconext. An SP in Manage can have other binding types, and can have the same URL for different bindings. If any other bindings are returned, ignore them, so we do not trigger an exception about duplicate ACS location URLs.
> Ignore ACS locations that do not have the HTTP-POST Binding.

- docker/Dockerfiledev
The prep_oc.sh script that was ran when building the OpenConext container would search the saml definition for the SPdashboard in /usr/local/etc. The dockerfile placed it in /tmp.
Building the openconext container will now import the SPdashboard saml entity in Manage again.
> Fix the location of the SPD saml definition so it is imported 

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/EntityChangeRequestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
Organization names are registered on the Service
and copied to the metadata of the entity. The copy action 
should not be applied to the entity data
fetched from Manage when used for comparison.
see: https://www.pivotaltracker.com/story/show/184014629
> Update changes of organization names to manage

- src/Surfnet/ServiceProviderDashboard/Application/Factory/EntityDetailFactory.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityChangeRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/ViewObject/EntityActionsTest.php
- tests/unit/Application/ViewObject/EntityTest.php
Only show the option 'Change request' in the action list of an  entity when an entity has pending change request.
see: https://www.pivotaltracker.com/story/show/183710218
> Show change request action only when available

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
- tests/webtests/EntityCreateSamlTest.php
For a SAML entity at least one ACS location is required.
The validation is placed only on the entity. Validation on the form by setting 
the required option of the CollectionType has the side effect that the collection input 
always needs a value even though locations have been entered.
see https://www.pivotaltracker.com/story/show/184195917
> Validate that at least one ACS location is present

- app/scss/components/connection_request.scss
The alignment of the plus button at the connection request was mixed up probable caused during a merge.
see: https://www.pivotaltracker.com/story/show/184325032
> Align plus button of connection request

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
An authorization check has been added to prevent creation of an oAuth client credential clients (ccc) when the option to add client credential clients is disabled.
see: https://www.pivotaltracker.com/story/show/183828026
> Throw exception on oauth_ccc when ccc is disabled

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateConnectionRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityPublishedController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/publishedProduction.html.twig
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/publishedProductionAndConnectionRequest.html.twig
When I  an OIDC entity is published to production, the modal with the secret and ClientID has to appear after submittance or skipping the connection request form. 
see: https://www.pivotaltracker.com/story/show/184477504
> Show secrets modal for new oidc entities after connection request

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateConnectionRequestController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/sendConnectionRequest.html.twig
The secrets of an OIDC were only displayed when the dialog of the connection request was skipped. This PR fixes this issue that the secrets are also shown when an connection request is posted.
see: https://www.pivotaltracker.com/story/show/184460472
> Display secrets after adding a connection request for an OIDC entity

- package.json
- yarn.lock
Semver <7.5.2 is vulnerable to Regular Expression Denial of Service attacs. See CVE-2022-25883
> Resolve semver to a safe version

- assets/Resources/metadata/privacy_questions.json
- docker-compose.yml
- migrations/Version20230620124841.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/PrivacyQuestions/PrivacyQuestionsCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/PrivacyQuestions/PrivacyQuestionsCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OauthClientCredentialsClientJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/PrivacyQuestions.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/DpaType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- tests/unit/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGeneratorTest.php
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
- tests/unit/Legacy/Repository/AttributesMetadataRepositoryTest.php
- tests/webtests/CreatePrivacyQuestionsTest.php
- tests/webtests/EditPrivacyQuestionsTest.php
PART 2 of the Privacy Questions overhaul
In the second part, I added the new fields. Which are the `dpaType` and the multilingual `PrivacyStatementUrl` (nl+en) fields. They are added throughout the entire stack.
While at it, I found out the Privacy Questions where not included upon entity update actions. That was also addressed in this PR.
> Introduce new privacy questions

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/DeletePublishedTestEntityCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/DeletePublishedTestEntityCommandHandlerTest.php
When a test entity is removed from manage, also push the updated metadata to EngineBlock and the OidcNg gateway.
`https://www.pivotaltracker.com/story/show/184915015`
> Push test metadata upon entity deletion

- assets/js/components/delete_member.ts
When pressing the delete membership button on the manageTeam page, the click on the anchor would be catched with the mousedown event listener. Propagation was stopped, but the mouseup/click event was still triggered. Drawing this behavior:
1. The team membership was removed via the mousedown event
2. The href was followed resulting in a visit to the api that handles the removal of the member. As the member was remove previously, that resulted in the error message that was described in the story
What was done to prevent this?
1. The listener was changed to be a click event listener
2. Both immediate propagation is stopped and 'preventDefault' is called on the event.
See: https://www.pivotaltracker.com/story/show/185585883
> Prevent teammember double delete drama

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGenerator.php
- tests/unit/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGeneratorTest.php
The JSON generator has been made more robust, only adding the questions (and associated answers) when they are present on the Service entity.
> When no privacy Q&A set, do not try to read them

- assets/js/components/service_switcher.js
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
1. The empty option was removed from the service switcher (was caused by a missing placeholder text)
2. Given you are admin and only one service is activated, the service overview of that service is now auto-loaded.
See: https://www.pivotaltracker.com/story/show/182154117
> Service switcher improvements

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/MailMessageFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
The twig template can now be passed to the mailer, and symfony takes care of rendering the template without the need to render it ourself.
> Set template on mail message correctly

- assets/js/components/change_member_role.ts
- assets/js/components/resend_invite.ts
When clicking certain buttons in the teams screens, events would be triggered multiple times. This was already fixed in #600. But other construct also used the mousedown event. That was fixed in this commit for the change member the resent invitation listeners. The issue was described in the storie mentioned below.
See: https://www.pivotaltracker.com/story/show/185785974
See: https://github.com/SURFnet/sp-dashboard/pull/600/files
> Prevent double actions

- assets/scss/pages/privacy_questions.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- templates/form/fields.html.twig
Each DPA type now has a dedicated tooltip as described in:
https://www.pivotaltracker.com/story/show/185441616
The hints are rendered inside the choices. 
The base form template needed an adjustment to allow the hint to show up. 
The hints rely on the existing tippy tooltip implementation. So no additional JS was required to add event listeners.
> Add DPA choice specific tooltips

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
Now that the individual dpa type options have their own tooltips, the parent tooltip has become redundant. And is removed in this commit.
See: https://www.pivotaltracker.com/story/show/183883449
Part of: https://github.com/SURFnet/sp-dashboard/pull/591
> Remove tooltip from DPA type parent element

- assets/js/components/collection_widget.test.ts
- assets/js/components/collection_widget.ts
- assets/scss/components/collection_widget.scss
- templates/form/fields.html.twig
By removing the readonly state when pressing the edit button, the value can now be modified. The collection widget was modified to allow for this behavior. Three fields currenlty utilize this widget (acs locations, redirect urls and the connection requests) The ACS and Redirect urls are affected by this change, as I thought it would be a good idea to start small. Editing the connection requests may come at a later stage.
See: https://www.pivotaltracker.com/story/show/185431458
Screenshots:
Disclaimer on the broken build:
- The integration test was fixed in #595 
- The failing webtest is a false positive
> Allow edits of the Collection widget entries

- docker/Dockerfile
PHP needs its config files whith .ini extension, not .conf
> Docker php config: Change .conf to .ini 

- package.json
- yarn.lock
The outdated Cypress dependencies caused security issues. They are upgraded here
> Upgrade JavaScript dependencies

- .env.dev
- .github/workflows/test-integration.yml
- README.md
- docker-compose-openconext.yml
- docker-compose.yml
We used a custom OpenConext container before. Since we use the [devconf](https://github.com/OpenConext/OpenConext-devconf) project for all docker related development, SPD will use that as well. Some work needs yet to be done to rewrite the integration tests to use the same environment.
you will need to checkout devconf in the same dir as  the sp-dashboard code 
codedir:
- sp-dashboard/
- OpenConext-devconf/
> Use devconf as basis for development.

- migrations/Version20240610074359.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
This additional field will show us when a service is created. It is not displayed anywhere in the UI (by design). It is just there for the TPMs to inform them for how long the SP has been granted access to the dashboard.
See: https://www.pivotaltracker.com/story/show/187715470
> Add `createdAt` to Service entity

- .env.test
- ci/qa/phpstan-baseline.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
- templates/EntityActions/deleteAction.html.twig
- templates/EntityActions/editAction.html.twig
- templates/EntityActions/overviewAction.html.twig
- tests/unit/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProviderTest.php
- tests/webtests/EntityDetailTest.php
- tests/webtests/WebTestCase.php
See: https://www.pivotaltracker.com/story/show/187684723
This PR concludes point 2 of the story mentioned above. In short, the edit and delete action-buttons would still be visible on the entity detail page. That allowed multiple remove jira tickets from being created. That was remedied in this PR by removing those buttons.
A web test was added, for which I created a means to create a fake jira ticket directly from test.
> Dont show edit and delete actions when removal requested

- assets/scss/pages/service-connection.scss
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
- templates/Service/my-services.html.twig
- tests/webtests/EntityDetailTest.php
- tests/webtests/ServiceCreateTest.php
- tests/webtests/ServiceSwitcherTest.php
1. The filter column is removed from the template as it is out of scope for now.
2. An additional translatable explanation text was added 
3. Webtests have been reinstated
> Remove filter column and add the extra explanation text

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOauthClientCredentialClientCommand.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OauthClientCredentialEntityType.php
The type of service should not be on the client credential entity forms. At first I implemented them on there, but never finished work on it, causing the CCC web tests to fail. That was fixed here.
> Disable type of service for oauth_ccc entities

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityAclController.php
- tests/webtests/EntityAclTest.php
As reported here: https://www.pivotaltracker.com/story/show/186876461/comments/241799189
The new ACL was applied to the `idps` and `acl` routes for an entity edit screen. I added a webtest to cover this feature in test.
> Only allow users that have membership of mentioned service

- ci/qa/phpstan-baseline.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ValueObject/EntityMergeAttribute.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Attribute.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
- tests/unit/Domain/Entity/Entity/AttributeListTest.php
A number of fields will be added in the arp. Besides source, value and motivation, use_as_name_id and "release_as" are added. If these already exist, they should be returned with the same values (analogous to "source" which we also leave untouched)
Before: 
```json
"arp" : {
"attributes" : {
"urn:mace:dir:attribute-def:givenName" : [ {
"source" : "idp",
"value" : "*",
"motivation" : "1243"
} ],
"urn:mace:dir:attribute-def:uid" : [ {
"source" : "idp",
"value" : "*",
"motivation" : "test"
} ]
}
```
After:
```json
"arp" : {
"attributes" : {
"urn:mace:dir:attribute-def:givenName" : [ {
"source" : "idp",
"value" : "*",
"motivation" : "1243",
"release_as" : "123",
"use_as_name_id" : true
} ],
"urn:mace:dir:attribute-def:uid" : [ {
"source" : "idp",
"value" : "*",
"motivation" : "test" …
```
> Add properties to the ARP values

- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Attribute.php
- tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
Occurences of `use_as_name_id` changed to `use_as_nameid`
> Rename use_as_nameid arp property

- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Constants.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- tests/webtests/EntityEditTest.php
- tests/webtests/Manage/Client/ClientResult.php
- tests/webtests/Manage/Client/FakeIdentityProviderClient.php
- tests/webtests/Manage/Client/FakeQueryClient.php
- tests/webtests/Manage/Client/template/ccc.json
- tests/webtests/Manage/Client/template/oidc10.json
- tests/webtests/Manage/Client/template/saml20_sp.json
- tests/webtests/WebTestCase.php
When the 'subjectType' or 'nameIdFormat' is unspecified. The matching form field is not displayed on the form. That way we do not allow the user to overwrite this value in Manage (which is explicitly set for that SP by a product owner)
To test this, the mock SP storage needed to track the nameIdFormat value as a manage entity. That requires quite some test code to be edited..
See: https://www.pivotaltracker.com/story/show/185952423
> Hide nameIdFormat when `unspecified`

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Constants.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Coin.php
- src/Surfnet/ServiceProviderDashboard/Domain/Service/ContractualBaseService.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
- tests/unit/Application/Service/EntityMergeServiceTest.php
- tests/unit/Domain/Entity/Entity/CoinTest.php
- tests/unit/Domain/Entity/Entity/MetaDataTest.php
- tests/unit/Domain/Service/ContractualBaseServiceTest.php
The new service will ensure the business rules are followed for this feature. The tests have been updated to cover the new Coin entry on the Manage entity.
See: https://www.pivotaltracker.com/story/show/187977233
> Write contractual base to production entities

- assets/scss/pages/service-connection.scss
The names of the services preivously were blue. Implying you can click on them. But they are no anchor or otherwise interactable. So having them grey makes more sense.
See: https://www.pivotaltracker.com/story/show/186881796/comments/242257354
> Unblue the `/connections` name column values

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
- tests/unit/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProviderTest.php
As of 17th of July it was possible to both be SurfConextResponsible AND have a regular ROLE_USER at the same time. This was already correctly handled by the Authz logic, but the menu did not yet show the correct menu items for the roles the user is authorized for..
That's what fixed here. At first I thought the SamlProvider was broken, hence the (cosmetic) change in the Test.
See: https://www.pivotaltracker.com/story/show/186881796/comments/242257534
> Show correct menu items according to the granted authorizations

- src/Surfnet/ServiceProviderDashboard/Application/Service/IdpService.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/IdpServiceInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceConnectionService.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityConnection.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/IdentityProviderRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/IdentityProviderClient.php
- tests/unit/Application/ViewObject/EntityConnectionTest.php
- tests/unit/Infrastructure/Manage/Client/IdentityProviderClientTest.php
- tests/unit/Infrastructure/Manage/Client/fixture/identity_provider_response.json
- tests/webtests/Manage/Client/FakeIdentityProviderClient.php
It makes sense to show all connected IdP's in the CSV export for the surfconext representative. When the ACL is set to allow all IdPs connected to the SP, we should list all IdPs of the test env there.
This can be a long list. But now we would only show the Organizations IdPs, and the explicitly marked test-idps.
See: https://www.pivotaltracker.com/story/show/187805216/comments/242257758
> Add all IdPs to the export when ACL allowAll=true

- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- templates/EntityEdit/edit.html.twig
The SAML, OIDC, CCC and RS entities now have translatable edit info texts based on the environment
See: https://www.pivotaltracker.com/story/show/187940731
> Create env based translations for entity forms

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveEntityCommandInterface.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOauthClientCredentialClientCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngResourceServerEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Factory/EntityDetailFactory.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
- src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php
- src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/Coin.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/EntityDiff.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Factory/SaveCommandFactory.php
- templates/EntityDetail/detail.html.twig
- templates/EntityDetail/detailBooleanField.html.twig
- tests/unit/Application/Metadata/JsonGeneratorTest.php
- tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
- tests/unit/Application/Metadata/fixture/oidc10_rp_response.json
- tests/unit/Application/Metadata/fixture/oidc10_rp_response_changed.json
- tests/unit/Application/Metadata/fixture/saml20_sp_response.json
- tests/unit/Application/Service/EntityMergeServiceTest.php
- tests/unit/Domain/Entity/Entity/CoinTest.php
- tests/unit/Domain/Entity/Entity/MetaDataTest.php
- tests/unit/Domain/Service/ContractualBaseServiceTest.php
- tests/webtests/EntityDetailTest.php
The SAML and OIDC entities now allow for setting the coin:ss:idp_visible_only metadata setting. See the story for the fine details.
See: https://www.pivotaltracker.com/story/show/187515050
> New field to set 'coin:ss:idp_visible_only' 

- .env.test
- .github/workflows/test-integration-webtest.yml
Example output:
https://github.com/SURFnet/sp-dashboard/actions/runs/11608163793
> When webtest fails, upload a screenshot of the error to github actions.

- .env.dev
- .env.dist
- README.md
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
- tests/webtests/EditServiceTest.php
- tests/webtests/fixtures/entity-copy/remote-entity-info.json
- tests/webtests/fixtures/entity-copy/remote-oidcng-entity-info.json
Prior to this change, the webtests would fail when ran in the dev env, unless the `team_prefix_default_stem_name` env was adjusted manually.
This change updates the .dist env and several webtest fixtures to use the updated stem.
See: https://www.pivotaltracker.com/n/projects/1400064/stories/179572218/comments/227653860
Also scouted: Fix wrong manage credentials in `.env.dev`
Scouted: Add missing `yarn encore dev` to Readme
> Fix webtests in dev env.

- .env.dev
- .env.dist
- ci/qa/phpstan-baseline.php
- migrations/Version20241029125655.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/InviteRepository.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/PublishTeamsRepository.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/CreateRoleResponse.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/HttpClient/Exceptions/RuntimeException/InviteException.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/InviteHttpClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/InviteRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/InviteResponseFactory.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Teams/Client/PublishEntityClient.php
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/unit/Infrastructure/Invite/InviteRepositoryTest.php
- tests/unit/Infrastructure/Teams/Client/TeamsPublishEntityClientTest.php
- tests/webtests/EditServiceTest.php
- tests/webtests/Manage/Client/FakeInviteRepository.php
- tests/webtests/Resources/config/services.yml
- tests/webtests/ServiceCreateTest.php
- tests/webtests/WebTestCase.php
- tests/webtests/fixtures/invite-role-create.json
Prior to this change, the Service was registered in teams, which is going to be removed.
This change registers the Service as a role in Invite, so an invite can be sent later.
See https://www.pivotaltracker.com/story/show/188011488
> Create role in invite when registering new service

- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/Command/Service/SendInviteCommand.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/SendInviteCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/Invite/CreateRoleRepository.php
- src/Surfnet/ServiceProviderDashboard/Domain/Repository/Invite/SendInviteRepository.php
- src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/SendInviteResponse.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/CreateRoleRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/SendInviteRepository.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/SendInviteResponseFactory.php
- tests/integration/Application/Command/SendInviteCommandTest.php
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/integration/Application/CommandHandler/Service/SendInviteCommandHandlerTest.php
- tests/unit/Infrastructure/Invite/InviteRepositoryTest.php
- tests/unit/Infrastructure/Invite/SendInviteRepositoryTest.php
- tests/webtests/Manage/Client/FakeCreateRoleRepository.php
- tests/webtests/Manage/Client/FakeSendInviteRepository.php
- tests/webtests/Resources/config/services.yml
- tests/webtests/ServiceCreateTest.php
- tests/webtests/WebTestCase.php
In a previous commit, a role was created in invite when adding a new
service.
This change, also sends the invite command to invite so invite sends an
actual invite email to the person to be invited.
See https://github.com/SURFnet/sp-dashboard/issues/1168
> After creating a Service, send an Invite through invite

- tests/webtests/WebTestCase.php
Prior to this change, the webtests would randomly fail with
StaleElementReferenceException errors.
This change attempts to work around those errors by adding a retry.
Most of the time, the error is thrown on the consent check.
> Attempt to remove StaleElementReferenceException errors from pipeline

- config/packages/doctrine.yaml
- tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
- tests/webtests/ServiceOverviewTest.php
Prior to this change, the ServiceOverviewTest would load the fixtures twice.
This would make doctrine complain about primary keys being forcefully reused on new enities.
This change does not load the fixtures twice, resolving the issue.
Prior to this change, doctrine would note that we need to make a decision whether to use savepoints or not.
This change explicitly enables savepoints, as Innodb engine and sqlite support savepoints.
This was always the default behavior, and by explicitly setting it to 
true, we keep it that way. Thil will tell doctrine that it can use 
nested database transactions.
Also rewrite test assertion to not rely on deprecated Hamcrest bundle.
> Address some deprecations

- assets/js/components/connection_request_widget.ts
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
- templates/form/fields.html.twig
- tests/webtests/CreateConnectionRequestTest.php
Prior to this change, when you enterd the form data, it was unclear you needed to press the + button in order to 'add' it. This change shows the list headers + a clarifying text to clarify this. The clarifying text should only be shown if there are no items in the list.
Resolves https://github.com/SURFnet/sp-dashboard/issues/1201
---
Prior to this change, when you would click '+' on an invalid row, then click 'Send', the row would become disabled while being invalid, effectively freezing the form, requiring a manual page refresh to continue.
This change will not disable the row unless the row is valid.
Old
https://github.com/user-attachments/assets/d98522a9-609f-45c7-90d1-cb72424de4d0
New
https://github.com/user-attachments/assets/3874871f-7c99-410c-a164-612d03a17617
> Improve UX of Create connection request form

- composer.json
- composer.lock
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
Prior to this change, the service container was wrongly configured, the wrong handler was specified for the SendInviteCommand.
---
```
Uncaught PHP Exception Error: \"Class \"Symfony\\Component\\HttpClient\\HttpClient\" not found\" at InviteHttpClient.php line 46
```
> Fix configuration bug

- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/InviteHttpClient.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Invite/InviteHttpClientUrlSanitizer.php
- tests/unit/Infrastructure/Invite/InviteHttpClientUrlSanitizerTest.php
Prior to this change, the api call to invite would fail because the relative path would collapse. This change ensures the baseUri and call path are absolute/relative when needed so the calls get executed as expected.
See https://symfony.com/doc/7.2/reference/configuration/framework.html#reference-http-client-base-uri
> Ensure correct invite url

- assets/scss/excludes/forms.scss
- assets/scss/pages/service_edit.scss
Prior to this change, the contrast on form labels was too low.
Resolves https://github.com/SURFnet/sp-dashboard/issues/1318
> Improve contrast on form labels

- src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/UpdateEntityIdpsCommand.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/validators.en.yml
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelected.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelectedValidator.php
- templates/EntityAcl/idps.html.twig
- tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelectedValidatorTest.php
- tests/webtests/EntityCreateOidcngTest.php
- tests/webtests/EntityCreateSamlTest.php
Prior to this change, when no idp was selected in the Entity IDP selection when publishing an Entity, the form validation would handle, and and error was thrown.
This change adds form validation that at least one IDP must be selected.
Resolves https://github.com/SURFnet/sp-dashboard/issues/1331
> Add validation: At least 1 idp must be selected

- templates/EntityAcl/idps.html.twig
This fixes the twig template to show the correct text
> The test IdP ACL page showed a text twice. 

- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
- src/Surfnet/ServiceProviderDashboard/Domain/Service/ContractualBaseService.php
- tests/integration/Application/CommandHandler/Entity/PublishEntityTestCommandHandlerTest.php
- tests/unit/Domain/Service/ContractualBaseServiceTest.php
Prior to this change, when saving a test entity, the contractual base field in manage would be set to null.
This is because the contractual base field is used for the production entities. Other random coin fields will not get overwritten.
This change makes sure the current value from Manage is reapplied, so sp-dasboard will not mutate the value.
Fixes https://github.com/SURFnet/sp-dashboard/issues/1343
> Fix: Contractual base gets overwritten in manage

- .github/workflows/test-integration.yml
- src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/EntityChangeRequestCommandHandler.php
- tests/integration/Application/CommandHandler/Entity/EntityChangeRequestCommandHandlerTest.php
Prior to this change, when a change request was sent, the contractualBase would be set to null, because it is not present in the form. This change updates the contractualbase if necessary on update.
The expected behaviour is:
When the field is not present, add it with the correct value 
When the field is present and the value is incorrect update it 
When the field is present and the value is correct, leave it untouched
Resolves https://github.com/SURFnet/sp-dashboard/issues/1343
> Fix: Don't reset contractual base on production entities

- .github/workflows/main.yml
- composer.lock
Prior to this change, an error occurred looking up jira issues, resulting in jira issues not being created. By updating this library, error should no longer occur as this version of the library does not do strict type checking.
> Fix for Jira tickets not being created

- composer.json
- composer.lock
Jira is updated and now returns null for the 'expand' field.
> Experimental fix for Jira issue.

- composer.json
- composer.lock
The previous commit does not use the correct version of the jira bundle, it did not include the previous fix.
This commit fixes that, including all fixes.
> Fix previous commit regression

- composer.json
- composer.lock
Prior to this change, since the jira update, tickets were no longer created because of errors.
The responses from Jira are changed, and this change does the minimal required fixes in order to create tickets again using a forked version of the lesstif/php-jira-rest-client library.
Fixes #1364
> Fix jira integration after jira update

- .env.dev
- ci/qa/phpstan-baseline.php
- src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
- tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
- tests/webtests/Manage/Client/FakePublishEntityClient.php
Prior to this change, parsing the response from manage failed because manage changed the output.
This change adapts to the new format so no incorrect error messages are shown.
Fixes https://github.com/SURFnet/sp-dashboard/issues/1382
> Adapt to updated manage response
