README.md
Vagrantfile
ansible/group_vars/all.yml
ansible/roles/app/tasks/mailcatcher.yml
ansible/roles/app/tasks/main.yml
ansible/roles/app/templates/xdebug.ini.j2
app/AppKernel.php
app/config/config.yml
app/config/config_dev.yml
composer.json
composer.lock

For a checklist of the features to be installed, see [Pivotal](https://www.pivotaltracker.com/story/show/150963310).

Perform base installation and configuration

---

build.xml
phpcs.xml
phpcs_tests.xml
phpunit.xml
tests/webtests/EntityListTest.php

This is just an exapmle testcase since there is nothing much to test
yet.

Add webtest for the entity list action

---

app/DoctrineMigrations/Version20171002152200.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php

Run: `bin/console doctrine:migrations:migrate` to incorporate the schema change in your working copy.
This is is one in a series of pull requests that will implement the feature described in [pivotal #150962638](https://www.pivotaltracker.com/story/show/150962638).
Next ticket: #27

 Change the datatype of Services id field

---

app/Resources/views/form/fields.html.twig
app/js/application.js
app/js/components/service_edit_attribute.js
app/scss/base/mixins.scss
app/scss/components/form.scss
app/scss/excludes/forms.scss
app/scss/pages/service_edit.scss
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/AttributeType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/EditServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/edit.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Supplier/create.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Supplier/edit.html.twig

Done:
- help balloons
- attribute fields (enable/disable)
- contact fieldset

Add theming for the service edit form

---

app/Resources/views/form/fields.html.twig
app/scss/components/wysiwyg.scss
docs/translations.md
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/EditServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/edit.html.twig

Added default translations
Added basic theming for the wysiwyg text output
Renamed the wysiwyg translation token names
Updated readme

Add translations for Service form

---

app/js/components/translation_ui.js
composer.lock
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

Bugs introduced in 30ee3a2 and 8de590b.

Fix bugs in translation messages.en.yml

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/SupplierController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/CreateSupplierType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Supplier/create.html.twig
tests/webtests/CreateSupplierTest.php
tests/webtests/Repository/InMemorySupplierRepository.php

Add test for create supplier command

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/edit.html.twig
src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Exception/MetadataFetchException.php
src/Surfnet/ServiceProviderDashboard/Legacy/Metadata/Fetcher.php
tests/webtests/EditServiceTest.php
tests/webtests/fixtures/metadata/invalid_metadata.xml

Provide friendly parse and fetch error messages

---

app/scss/excludes/forms.scss

Improve the visibility of error messages

---

ansible/group_vars/all.yml
ansible/roles/spdashboard/templates/parameters.yml.j2

I've added the administrator_team to the parameters.yml.j2 ninja template file.

Update parameters template with admin team name

---

app/DoctrineMigrations/Version20171030094027.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/PrivacyQuestionsController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/CreateServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/EditServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
tests/webtests/EditServiceTest.php

**Review notes**
Don't forget to run the migration.
**Tasks**
1. [x] Add the toggle to the form
1. [x] Implement security measures
**Checklist**

Enable the Privacy Questions admin toggle

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeleteEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/DeleteEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/DeleteEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDelete/delete.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
tests/integration/Application/CommandHandler/Entity/DeleteEntityCommandHandlerTest.php
tests/webtests/EntityDeleteTest.php

Implement the deletion of draft entities

---

src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityListController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
tests/webtests/EditServiceTest.php
tests/webtests/EntityDeleteTest.php
tests/webtests/EntityListTest.php
tests/webtests/Resources/config/services.yml
tests/webtests/ServiceSwitcherTest.php
tests/webtests/WebTestCase.php

Show services from manage in the entity list

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

Make ticketNumber information balloon translatable

Make ticketNumber information balloon translatable

---

app/Resources/metadata/sp_dashboard.json
src/Surfnet/ServiceProviderDashboard/Application/Factory/SpDashboardMetadataFactory.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
tests/integration/Application/CommandHandler/Entity/PublishEntityCommandHandlerTest.php
tests/unit/Infrastructure/Manage/Client/PublishEntityClientTest.php
tests/unit/Legacy/Repository/AttributesMetadataRepositoryTest.php

Missing where:
- Application url
- Eula url
- Metadata url

Add missing metadata Manage publish action

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EditEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/PrivacyQuestions/PrivacyQuestionsFormBuilder.php

The title says it all.
The change was restricted to the EntityEdit form and the PrivacyQuestions form.

Increase the height of textareas

---

app/scss/components/table.scss

Fine-tune padding in the entity list table

---

src/Surfnet/ServiceProviderDashboard/Domain/Entity/Contact.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php

Resolves https://www.pivotaltracker.com/story/show/152479588
**Checklist**
We hebben geen functionele tests voor dit onderdeel.

Prevent saving duplicate contact-service relations

---

app/scss/components/actions.scss
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/CopyEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/CopyEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCopyController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
tests/integration/Application/CommandHandler/Entity/CopyEntityCommandHandlerTest.php
tests/webtests/EntityCopyTest.php

Copy published test entity to become production-draft entity

---

src/Surfnet/ServiceProviderDashboard/Domain/Entity/Contact.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
tests/webtests/WebTestCase.php

Previous implementation did not take into account possible revocation
of a service to a contact.

Allow service to be removed from contact

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig

This is not yet implemented, so don't offer the option in the menu.

Remove 'view' from context menu

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

Updates the privacy question label texts adding numbering. Also a duplicate question label was corrected (question 1 and 2 where the same)

Add numbering to question labels

---

ansible/roles/spdashboard/defaults/main.yml
ansible/roles/spdashboard/templates/parameters.yml.j2

This PR makes variables of the email addresses so test emails do not end up in our support system

Ansible: Make email addresses configurable

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php

Fix error when user is not member of any group

---

app/Resources/views/form/fields.html.twig
app/js/application.js
app/js/components/tooltips.js
app/scss/components/form.scss
package.json
yarn.lock

https://www.pivotaltracker.com/story/show/152539381

Implement better tooltips

---

composer.json
composer.lock
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Handler/ProcessSamlAuthenticationHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/SamlInteractionProvider.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Token/SamlToken.php

Any usages of the old (not namespaced) SAML2 library usages have been replaced.

Upgrade Stepup-saml-bundle to version 3.0.0

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

**Information popups where added for several fields**
See pivotal for more information.
Fixes: #154956441

Add balloons for several entity form fields

---

app/scss/pages/service_edit.scss
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/validators.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityEdit/edit.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributes.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributesValidator.php
tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/HasAttributesValidatorTest.php
tests/webtests/EntityPublishToProductionTest.php
tests/webtests/EntityPublishToTestTest.php

See [pivotal](https://www.pivotaltracker.com/story/show/156912587).

Require at least one attribute before publication

---

src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGenerator.php
tests/unit/Application/Metadata/JsonGenerator/PrivacyQuestionsMetadataGeneratorTest.php

See [pivotal](https://www.pivotaltracker.com/story/show/157842831).

Format dates as RFC3339 dates

---

app/js/components/validation.js
app/scss/excludes/forms.scss
app/scss/pages/base.scss
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/EntityType.php

See [pivotal](https://www.pivotaltracker.com/story/show/152807745).

Various validation improvements for the entity form

---

README.md
ansible/files/certs/shib-sp.crt
ansible/group_vars/all.yml
docs/saml-dev-setup.md
docs/ubiquitous_language.md

See commits for more details. In addition, the readme's where updated when applicable.

Repair Ansible provisioning

---

Vagrantfile
composer.lock
var/SymfonyRequirements.php

This is the result of a `composer update` action in develop.
Mainly to get rid of the security checker warning, but also to stay up to date on other package changes. 
```
robrichards/xmlseclibs (3.0.1)
------------------------------
* (no CVE ID): Filter input to avoid XPath injection
https://github.com/robrichards/xmlseclibs/commit/649032643f7aac493e91ca318da0339aec72aa4a
! [NOTE] This checker can only detect vulnerabilities that are referenced in   
!        the SensioLabs security advisories database. Execute this command     
!        regularly to check the newly discovered vulnerabilities.              
```

Update composer dependencies

---

app/DoctrineMigrations/Version20181106121253.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php

The change is reflected in the migration. The change is described in
greater detail in this story and matches task 1 and 2 from that story:
https://www.pivotaltracker.com/story/show/161341178

Add status fields to the Service entity

---

Vagrantfile
ansible/group_vars/all.yml
ansible/group_vars/override.yml
ansible/roles/manage-gui-prod/defaults/main.yml
ansible/roles/manage-gui-prod/meta/main.yml
ansible/roles/manage-gui-prod/tasks/main.yml
ansible/roles/manage-gui-prod/templates/manage.conf.backdoor.j2
ansible/roles/manage-gui-prod/templates/manage.conf.j2
ansible/roles/manage-gui-prod/vars/main.yml
ansible/roles/manage-server-prod/defaults/main.yml
ansible/roles/manage-server-prod/files/metadata_configuration/saml20_idp.schema.json
ansible/roles/manage-server-prod/files/metadata_configuration/saml20_sp.schema.json
ansible/roles/manage-server-prod/files/metadata_configuration/single_tenant_template.schema.json
ansible/roles/manage-server-prod/files/metadata_export/saml20_idp.xml
ansible/roles/manage-server-prod/files/metadata_export/saml20_sp.xml
ansible/roles/manage-server-prod/files/metadata_export/single_tenant_template.xml
ansible/roles/manage-server-prod/files/metadata_templates/saml20_idp.template.json
ansible/roles/manage-server-prod/files/metadata_templates/saml20_sp.template.json
ansible/roles/manage-server-prod/files/metadata_templates/single_tenant_template.template.json
ansible/roles/manage-server-prod/handlers/main.yml
ansible/roles/manage-server-prod/meta/main.yml
ansible/roles/manage-server-prod/tasks/main.yml
ansible/roles/manage-server-prod/templates/application.yml.j2
ansible/roles/manage-server-prod/templates/logback.xml.j2
ansible/roles/manage-server-prod/templates/manage-api-users.yml.j2
ansible/roles/manage-server-prod/vars/main.yml
ansible/vagrant.yml

This PR will install a second installation of Manage in the SP Dashboard VM. This instance is called manage-prod (sometimes referred to in the ansible tasks as manage-prd). The instance will be used to publish production entities to from SP Dashboard.

Install the production Manage instance

---

phpcs_tests.xml
src/Surfnet/ServiceProviderDashboard/Application/Assembler/ServiceStatusAssembler.php
src/Surfnet/ServiceProviderDashboard/Application/Dto/ServiceStatusDto.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityList.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/Api/ServiceController.php
tests/unit/Application/Assembler/ServiceStatusAssemblerTest.php

In order to have the service states visualized we need an api
endpoint to retrieve the data so we could represent it to the
user in a fancy way.
https://www.pivotaltracker.com/story/show/161719597

Add an endpoint to retrieve the service states

---

ansible/roles/spdashboard/defaults/main.yml
ansible/roles/spdashboard/tasks/install-branch.yml
ansible/roles/spdashboard/tasks/main.yml
ansible/roles/spdashboard/templates/parameters.yml.j2

A second manage instance is configured in the SPdashboard configuration.
Some minor Ansible fixes are added to this PR

Ansible: Add second manage & other improvements

---

app/Resources/views/modal.html.twig
app/js/application.js
app/js/components/modal.js
app/js/components/modal.ts
app/js/type_definitions.ts
app/scss/components/form.scss
app/scss/components/modal.scss
app/scss/pages/choose_entity_type.scss
docs/index.md
docs/third_party_packages.md
package.json
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ChooseEntityTypeType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityType/type.html.twig
yarn.lock

See individual commits for more details.
This PR should be merged into #174

Show the choose entity type form in a modal

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeleteCommandFactory.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/DeleteServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/DeleteServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Provider/EntityQueryRepositoryProvider.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Domain/Repository/ServiceRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Command/Service/ResetServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/CommandHandler/Service/ResetServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/DeleteServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/ServiceRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/delete.html.twig
tests/integration/Application/CommandHandler/Service/DeleteServiceCommandHandlerTest.php
tests/unit/Application/Command/DeleteCommandFactoryTest.php
tests/unit/Application/Provider/EntityQueryRepositoryProviderTest.php
tests/unit/Application/Service/EntityServiceTest.php
tests/unit/Infrastructure/DashboardBundle/CommandHandler/Service/ResetServiceCommandHandlerTest.php
tests/webtests/ServiceDeleteTest.php

Delete a service and its entities.
Note that requesting the deletion of a published production entity is yet to be built. And awaits details in regards to the required Jira workflow.
For functional details, see the pivotal story.
https://www.pivotaltracker.com/story/show/154841957

Enable deleting of services

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeleteCommandFactory.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/DeleteServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Dto/EntityDto.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/Service/ServiceStatusService.php
tests/integration/Application/CommandHandler/Service/DeleteServiceCommandHandlerTest.php
tests/unit/Application/Command/DeleteCommandFactoryTest.php
tests/unit/Application/Service/ServiceStatusServiceTest.php

For all the details see:
https://www.pivotaltracker.com/story/show/162298797

Stop using the Entity view object everywhere 

---

docs/index.md
docs/jira.md
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeleteCommandFactory.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/RequestDeletePublishedEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/DeleteServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/DeleteServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Dto/EntityDto.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketService.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
tests/integration/Application/CommandHandler/Service/DeleteServiceCommandHandlerTest.php
tests/unit/Application/Command/DeleteCommandFactoryTest.php
tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php

This is the first part of a multi stage change set. For details check the [pivotal story](https://www.pivotaltracker.com/story/show/162124271)
To test this feature
1. Set the correct jira credentials in the parameters.yml file. To build a local Jira test instance, see 
f23db2c.
1. Possibly update the custom field identifier for the entity id in the [IsueFieldFactory](https://github.com/SURFnet/sp-dashboard/blob/0525a6c40ef01732db0698150e2b3993ce3f23ee/src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php#L26) This will be made configurable in the parameters.yml at a later stage!
1. Delete a published prod entity in the enitty overview of one of your services.

Create a delete published production entity request Jira ticket

---

app/DoctrineMigrations/Version20181127140634.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketService.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/EntityRemovalRequest.php
src/Surfnet/ServiceProviderDashboard/Domain/Repository/EntityRemovalRequestRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/EntityRemovalRequestRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
tests/unit/Application/Service/TicketServiceTest.php

Adds the new entity (run the migration)
And integrates it into the RequestDeletePublishedProductionEntityCommandHandler.

Add the EntityRemovalRequest entity and integrate it in the delete request flow

---

ansible/roles/spdashboard/defaults/main.yml
ansible/roles/spdashboard/templates/parameters.yml.j2
app/config/parameters.yml.dist
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Factory/IssueFieldFactory.php
tests/unit/Infrastructure/Jira/Factory/IssueFieldFactoryTest.php

Task 3 of https://www.pivotaltracker.com/story/show/162124271
~~For now, this PR was built on top of #178~~ after merging 178 this branch was rebased onto develop.

Make Jira issue and project fields configurable

---

tests/integration/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandlerTest.php
tests/unit/Infrastructure/Jira/Service/IssueServiceTest.php
tests/webtests/EntityDeleteTest.php

No Jira mock client has been created yet. This did not add much added value at this point.

Additional Jira test coverage

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoter.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Identity.php
tests/unit/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoterTest.php
tests/webtests/EntityDeleteTest.php

By using a voter, the authorization can be tested against the actual
manage entity.

Improve entity delete authorization

---

src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/CopyEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Dto/EntityDto.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Ticket.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoter.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Attribute.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/AttributeList.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Coin.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Contact.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ContactList.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Logo.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/MetaData.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/Organization.php
tests/integration/Application/CommandHandler/Entity/CopyEntityCommandHandlerTest.php
tests/integration/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandlerTest.php
tests/unit/Infrastructure/DashboardBundle/Security/Voter/ManageEntityAccessGrantedVoterTest.php
tests/unit/Infrastructure/Manage/Client/QueryClientTest.php
tests/unit/Infrastructure/Manage/Client/fixture/read_response.json
tests/unit/Infrastructure/Manage/Dto/ManageEntityTest.php
tests/unit/Infrastructure/Manage/Dto/fixture/saml20_sp_response.json
tests/webtests/EntityDeleteTest.php

Previously we just used the array response from Manage. This PR converts the response to a DTO. Making it easier to work with.

Handle Manage response more elegantly

---

app/scss/components/entity_detail.scss
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Contact.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/actionsForDetail.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/actionsForList.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/cloneAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/copyAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/deleteAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/editAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/viewAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailAttributeField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailContactField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailFormattedField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailTextField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityList/list.html.twig
tests/unit/Application/ViewObject/EntityTest.php
tests/webtests/EntityDetailTest.php

Display entity details

---

app/scss/components/entity_detail.scss
app/scss/components/form.scss
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Contact.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityActions/viewAction.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailAttributeField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailContactField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailFormattedField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailTextField.html.twig
tests/webtests/EntityDetailTest.php

See https://www.pivotaltracker.com/story/show/162412987 for further details. The commit shows more about the adjustments that have been made from #188

Implement the entity detail view part II

---

composer.json
composer.lock

Other dependencies have also been upgraded. This change was triggered
by a composer update.
See: https://www.pivotaltracker.com/story/show/162574278

Upgrade Symfony & Security checker

---

ansible/roles/spdashboard/defaults/main.yml
ansible/roles/spdashboard/templates/parameters.yml.j2
app/config/parameters.yml.dist
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityActions.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
tests/integration/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandlerTest.php
tests/unit/Application/Service/EntityServiceTest.php

This concludes the changes described in https://www.pivotaltracker.com/story/show/162439394. And specifically fixes task 3 and 4.
See the ticket for more details.

Read the Jira delete request status

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php

The error message should be more specific and the error should be
placed more closely to the element. Also the background color of the
element should be adjusted to reflect the error.

Fix the error for the redirect uri collection

---

app/Resources/views/form/fields.html.twig
app/js/components/collection_widget.ts
app/js/components/validation.js
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php

At least one redirectUri should be set and this was not covered by
the frontend input validation.
The redirectUri needs to be added to the collection if data is set but
not added to the redirectUri collection.

Fix redirect uri validation

---

src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Entity.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/ManageEntity.php
tests/webtests/EntityCreateOidcTest.php

The clientId needs to be shown as entityId.

Fix oidc clientId encoding presentation

---

ansible/roles/spdashboard/files/makeRelease.sh

This will save 35.000 files for the release :)

Makerelease: Make sure the node_modules dir is removed

---

CHANGELOG.md
composer.lock

To harden against CVE-NONE-0001

Upgrade Twig

---

ansible/roles/spdashboard/tasks/install-branch.yml
ansible/roles/spdashboard/tasks/main.yml
ansible/roles/spdashboard/tasks/spdashboardvm.yml

Removed redundant translation extractions and cleaned up some yum install commands.

Ansible cleanup

---

src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Issue.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/IssueCollection.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/DashboardExtension.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services_dev.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
tests/integration/Application/CommandHandler/Entity/RequestDeletePublishedEntityCommandHandlerTest.php
tests/unit/Domain/ValueObject/IssueCollectionTest.php
tests/unit/Infrastructure/DashboardBundle/Jira/Repository/IssueRepositoryTest.php

In order to allow local development without the need of a jira
server a repository is added to reproduce the behavior of jira.
To prevent coupling with third party dependencies a couple of domain
specific valueobjects were added to return from the repositories.
https://www.pivotaltracker.com/story/show/165993367

Add issue repository for testing

---

CHANGELOG.md
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeletePublishedProductionEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/DeletePublishedTestEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityTestCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveOidcEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/SaveSamlEntityCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/UpdateEntityAclCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Service.php
src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/Secret.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Command/Service/SelectServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Console/CleanOldProductionEntitiesCommand.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityControllerTrait.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Menu/Builder.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/EntityRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/UniqueEntityIdValidator.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Service/IdentityService.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Value/TimeFrame.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Http/Exception/MalformedResponseException.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Http/Exception/RequestException.php

This fixes all level 1 issues and most of the level 2 stuff.
https://www.pivotaltracker.com/story/show/166790449

Fix various phpstan reported issues

---

src/Surfnet/ServiceProviderDashboard/Application/Service/LoadEntityService.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml

See: https://www.pivotaltracker.com/story/show/167510179

 Set the oidcn TNG specific playground urls

---

src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/MetaData.php
tests/unit/Application/Metadata/JsonGeneratorTest.php

When pushing an OIDC entity to manage the signature method
wasn't pushed.
https://www.pivotaltracker.com/n/projects/1400064/stories/166838510

Push signature method to manage for OIDC

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php

As requested in: https://www.pivotaltracker.com/story/show/167511241/comments/206159247

Set authorization code as default grant type

---

src/Surfnet/ServiceProviderDashboard/Application/Parser/OidcngSpdClientIdParser.php
src/Surfnet/ServiceProviderDashboard/Application/Service/LoadEntityService.php
tests/unit/Application/Parser/OidcngSpdClientIdParserTest.php
tests/unit/Application/Service/LoadEntityServiceTest.php
tests/webtests/EntityCopyTest.php
tests/webtests/fixtures/entity-copy/remote-oidcng-entity-info.json

Only for OIDC TNG entities (RP & RS) should this logic be applied.
https://www.pivotaltracker.com/story/show/168452265

Prepend the https protocol after production copy

---

ansible/roles/spdashboard/defaults/main.yml
ansible/roles/spdashboard/templates/parameters.yml.j2
app/config/parameters.yml.dist
src/Surfnet/ServiceProviderDashboard/Domain/Service/OidcCreateEntityEnabledMarshaller.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityCreateController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/ProtocolChoiceFactory.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Service/AuthorizationService.php
tests/unit/Infrastructure/DashboardBundle/Form/Entity/ProtocolChoiceFactoryTest.php
tests/unit/Infrastructure/DashboardBundle/Service/AuthorizationServiceTest.php

The toggle is configured in the parameters.yml config file. And a marshaller is tasked with informing the application if the toggle is enabled or disabled.
https://www.pivotaltracker.com/story/show/168783027

Add oidc create feature toggle

---

composer.json
composer.lock

Symfony is upgraded to the latest 3.4 version.
Added platform and optimize autoloader settings in the Composer config section.

Update Symfony to 3.4.36

---

ansible/roles/spdashboard/tasks/spdashboardvm.yml
ansible/roles/tls/tasks/main.yml
ansible/vagrant.yml

The HTTPS certificate wasn't valid anymore. This PR creates a selfsigned certificate on the VM, using the ansible openssl modules.

Ansible: Add tls role which creates selfsigned certificates.

---

app/js/components/collection_widget.ts
yarn.lock

To prevent security issues, and to make other JS dependencies up to date.

Update JavaScript packages

---

app/js/components/validation.js
app/js/components/validator_helper.test.ts
app/js/components/validator_helper.ts
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php

This validation was added to the parsley validator. This should be sufficient validation. As when Javascript is disabled you wouldnt be able to submit the form with redirect uris.
See https://www.pivotaltracker.com/story/show/171620767

Allow loopback addresses for redirect uris

---

app/Resources/views/base.html.twig
app/scss/components/header.scss

Title was changed:
- to be blue
- normal cased
- text moved closer to logo
https://www.pivotaltracker.com/story/show/165311250

Match SPD header styling match that of IdPD

---

app/DoctrineMigrations/Version20200608111455.php
app/js/components/mock/service_create_form.html
app/js/components/mock/service_edit_form.html
app/js/components/service_form.test.ts
app/js/components/service_form.ts
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/CreateServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Service/EditServiceCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/CreateServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Service/EditServiceCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DataFixtures/ORM/WebTestFixtures.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Service/ServiceType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
tests/integration/Application/CommandHandler/Service/CreateServiceCommandHandlerTest.php
tests/integration/Application/CommandHandler/Service/EditServiceCommandHandlerTest.php
tests/webtests/ServiceCreateTest.php

Added the two institution fields (id and guid). Of which the id field will only be visible when the service type is 'institution'.
Be advised, a migration was added in order to persist said fields.
https://www.pivotaltracker.com/story/show/163754504

Add institution fields to Service

---

app/scss/components/table.scss
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
src/Surfnet/ServiceProviderDashboard/Domain/Repository/QueryEntityRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailResourceServersField.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/QueryClient.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Dto/OidcngClient.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Exception/UnexpectedResultException.php
tests/unit/Application/Service/LoadEntityServiceTest.php

More detailed resource server information (and a link to its detail screen) are added in this PR.
See: https://www.pivotaltracker.com/story/show/171620286

Display more detailed resource servers in client detail view

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

This translation was missed in #347
https://www.pivotaltracker.com/story/show/169340980/comments/215466922

Add entity.edit.information.redirectUrls to translations

---

src/Surfnet/ServiceProviderDashboard/Application/Service/EntityMergeService.php

https://www.pivotaltracker.com/story/show/175288695

Ensure client secret set on copy to production

---

docker/php-fpm/Dockerfile

Delete the symfony cache after the installation

Docker php fpm: Clear cache after installation

---

.travis.yml
docker/Dockerfile
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Service/EntityService.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
tests/webtests/CommandHandler/MockPublishEntityToProductionCommandHandler.php

The detail screen showed illegal entity options for the published entities.
https://www.pivotaltracker.com/story/show/175535045

Set correct publication state for prod entities

---

.travis.yml
bin/securityChecker.sh
build.xml
composer.json
composer.lock
package.json
yarn.lock

Removed the no longer maintained SensioLabs Security Checker and replaced it with Local PHP Security Checker.
https://github.com/fabpot/local-php-security-checker

Update security checker utilizing local security checker

---

docker/conf/000-default.conf

Add  Referrer-Policy "origin-when-cross-origin" to the httpd docker image

Apache: Set the Referer policy header

---

docker/Dockerfile
docker/Dockerfiledev
docker/conf/10-docker-opcache-openconext.conf
docker/conf/zz-docker.conf

Add opcache to the FPM docker image: This speeds up the application considerably

Install and configure opcache

---

src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityList.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/Service.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Service.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig

Prior to this change, production entities could not be published even if test entities were published.
This change ensures production entities can be published if test entities were published.
Pivotal issue at: https://www.pivotaltracker.com/story/show/177677810

Correct publishability of production entities

---

docker/conf/000-default.conf

- disable TRACE & TRACK methods
- disable showing the Apache version in the headers

Apache: Configuration changes

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php

The oidcng entry form showed the translations for the saml form

Show correct translations for oidc attributes

---

.github/workflows/main.yml

You can now build a container on demand through the GH webinterface

GH actions: Run on dispatch

---

app/scss/components/modal.scss
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/inviteModal.html.twig

Prior to this change, there was a regression regarding the modal functionality.  This was broken everywhere save for the membership management.
This change ensures all modals work.
See pivotal @:
- https://www.pivotaltracker.com/n/projects/1400064/stories/180874369
- https://www.pivotaltracker.com/n/projects/1400064/stories/180874379

Fix modal problems

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/DeleteManageEntityClient.php
tests/unit/Infrastructure/Manage/Client/DeleteEntityClientTest.php

https://www.pivotaltracker.com/story/show/180861173

Correct faulty protocol mapping on oauth2 resource server and add a test

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailAttributeField.html.twig
tests/webtests/EntityDetailTest.php

- Remove motivation placeholder from view entity page
- Add webtest for detail attributes
https://www.pivotaltracker.com/story/show/178674074

Remove motivation placeholder from view entity page

---

app/js/components/change_member_role.ts
app/js/components/delete_member.ts
app/js/components/invite_member.ts
app/js/components/resend_invite.ts
app/scss/components/actions.scss
app/scss/components/drop_down_actions.scss
app/scss/excludes/forms.scss
app/scss/pages/manageTeams.scss
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/Table/actions.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/Table/role.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/Table/roleCell.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/inviteModal.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Teams/teamTable.html.twig

-Rework the drop downs to no longer use selects, in order to be able to style them better & use icons.
-Fix issues with styling to be more inline with other drop downs.
https://www.pivotaltracker.com/story/show/181352823

Fix missing team role icons and make multiple ui improvements

---

src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator/ArpGenerator.php
tests/unit/Application/Metadata/JsonGenerator/ArpGeneratorTest.php
tests/unit/Application/Service/LoadEntityServiceTest.php
tests/webtests/fixtures/entity-copy/remote-oidcng-entity-info.json

See: https://www.pivotaltracker.com/story/show/181121296

Refrain from adding epTID for OIDCNG

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/PrivacyQuestionsController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Privacy/form.html.twig
tests/webtests/EditPrivacyQuestionsTest.php

see: https://www.pivotaltracker.com/story/show/182246029

Show flash message when privacy messages are changed

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDeleteController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityEditController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/ServiceController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityPublished/publishedTest.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/FlashMessage/flashMessages.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/admin_overview.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
tests/webtests/EntityCreateOidcngResourceServerTest.php
tests/webtests/EntityDeleteTest.php

see: https://www.pivotaltracker.com/story/show/182246029

Visual feedback after creating, editing and deleting a service or entity

---

docker/Dockerfile
docker/Dockerfiledev
docker/conf/10-timezone-openconext.ini

See: https://www.pivotaltracker.com/story/show/183402970

Set the Timezone on the PHP FPM container

---

app/config/attributes.json
src/Surfnet/ServiceProviderDashboard/Application/Factory/EntityDetailFactory.php
src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/AttributeServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetail.php
src/Surfnet/ServiceProviderDashboard/Application/ViewObject/EntityDetailAttribute.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityAclController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Controller/EntityDetailController.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Dto/AttributeDetail.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Dto/AttributeDetailLanguage.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Dto/AttributeInterface.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Dto/NullAttribute.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Repository/AttributeRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detail.html.twig
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/EntityDetail/detailAttributeField.html.twig
tests/integration/Legacy/Metadata/fixture/attributes.json
tests/unit/Application/Factory/EntityDetailFactoryTest.php
tests/unit/Application/Factory/fixture/saml20_sp_response.json
tests/unit/Application/Metadata/fixture/attributes.json
tests/unit/Application/Service/AttributeServiceTest.php
tests/unit/Application/Service/fixture/attributes.json
tests/unit/Infrastructure/DashboardBundle/Dto/AttributeTest.php
tests/unit/Infrastructure/DashboardBundle/Repository/AttributeRepositoryTest.php
tests/unit/Infrastructure/DashboardBundle/Repository/Fixtures/attributes.json

My recomendation is to review this PR on a commit basis. Each commit clearly (hopefully) states what task was performed to achieve a goal.
This PR addresses task 5 and 6 of https://www.pivotaltracker.com/story/show/182220241

Display the attributes on the entity detail screen using the new attributes service

---

app/scss/components/service_status.scss
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/views/Service/overview.html.twig
tests/webtests/ServiceOverviewTest.php

The h2 title became wrapped up in the service edit buttons. That was rectified here.
Secondly the h2 title itself received a healthy bottom margin. Making it more separated from the button bar.

Repair Service overview h2 title issue

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/EntityTypeFactory.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OauthClientCredentialEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
tests/webtests/EntityEditTest.php

During the creation of an entity, the submit button in the form is labeled Publish. When an entity is edited the label name is Change request.
see: https://www.pivotaltracker.com/story/show/183736253

Change button label to Change Request when editing an entity

---

CHANGELOG.md
src/Surfnet/ServiceProviderDashboard/Domain/Entity/ManageEntity.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Factory/EntityTypeFactory.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OauthClientCredentialEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngResourceServerEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
tests/unit/Infrastructure/DashboardBundle/Factory/EntityTypeFactoryTest.php
tests/unit/Infrastructure/Manage/Dto/ManageEntityTest.php
tests/unit/Infrastructure/Manage/Dto/fixture/saml20_sp_requested.json
tests/webtests/EntityEditTest.php

For new production entities or template based entities the submit
button label is 'Publish' and 'Change' otherwise.
see: https://www.pivotaltracker.com/story/show/184302283

Repair button change request

---

.github/workflows/daily-security-check.yml
.github/workflows/test-integration.yml
ci/qa/security
composer.json

QA builds should not break and halt the development process.
1. Security scanning is performed periodically via weekly sceduled IRL checks
2. By utilizing the security scanner from the OpenConext .github actions templates
3. By relying on the dependabot

Update security scanner policy

---

composer.lock
yarn.lock

Update the JS and PHP libraries within their version constraints.

Install security updates

---

.env.dist
config/packages/dev/framework.yaml
config/packages/dev/services.yml
config/packages/prod/framework.yaml
config/packages/prod/services.yml
config/packages/test/framework.yaml
config/packages/test/services.yml
config/services.yaml
docker-compose.yml
docs/jira.md
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/DependencyInjection/Compiler/IssueRepositoryCompilerPass.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php

The jira_enable_test_mode parameter is read. By default, the setting is set to be enabled. This aids dev + test environments.

Repair jira_enable_test_mode feature flag

---

src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/PublishEntityProductionCommand.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/ResetOidcSecretCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/config/services.yml
tests/integration/Application/CommandHandler/Entity/PublishEntityProductionCommandHandlerTest.php
tests/integration/Application/CommandHandler/Entity/ResetOidcSecretCommandHandlerTest.php

1. [Push client reset to correct environment](https://github.com/SURFnet/sp-dashboard/commit/4060fcf1f99fd60022e5f95c1e44f946e2eb325b) -> https://www.pivotaltracker.com/story/show/185786023
2. [Refrain from making Jira ticket on client reset](https://github.com/SURFnet/sp-dashboard/pull/607/commits/007855d51a6958db62e84ffad5ef599f8573d30c) -> https://www.pivotaltracker.com/story/show/184962438

Improve client reset behavior

---

yarn.lock

Hardening against vulnerability described here: 
blamer vulnerable to Arbitrary Argument Injection via the blameByFile() API #76

Upgrade JS CPD upgrading blamer in the process

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml

We have fixed this in production by changing the translations. Better to fix this in code

Fix the mixup of DPA_TYPE_MODEL_SURF and DPA_TYPE_IN_SURF_AGREEMENT

---

src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/EntityChangeRequestCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/GeneratorInterface.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGeneratorStrategy.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OauthClientCredentialsClientJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketService.php
src/Surfnet/ServiceProviderDashboard/Application/Service/TicketServiceInterface.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/ChangeRequestRevisionNote.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/JiraTicketNumber.php
src/Surfnet/ServiceProviderDashboard/Domain/Repository/EntityChangeRequestRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/DevelopmentIssueRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Jira/Repository/IssueRepository.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/EntityChangeRequestClient.php
tests/unit/Application/Metadata/JsonGeneratorTest.php
tests/unit/Application/Metadata/OauthClientCredentialsClientJsonGeneratorTest.php
tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php
tests/webtests/Manage/Client/FakeEntityChangeRequestClient.php

The change request would only include the optional comment that can be set in the form. We want some additional information.
To achieve that goal a couple of changes were made;
1. The proposed change is first molded into a Jira ticket
2. The ticket number is then used in the change request 'commit message'
3. Finally the change request is saved to Jira.
See: https://www.pivotaltracker.com/story/show/186241167

Improve the Change Request revision notes

---

ci/qa/phpcpd

phpcpd had an old (wrong) parameter in its script. Fixed it.

Fix phpcpd

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProvider.php
tests/unit/Infrastructure/DashboardSamlBundle/Security/Authentication/Provider/SamlProviderTest.php

At the same time. This entails rearanging the SamlProvider slightly.
Tests where made to reflect the combinations between the roles

Allow both ROLE_USER&SURFCONEXT_REPRESENTATIVE

---

.github/workflows/test-integration-webtest.yml
ci/qa/phpunit
ci/qa/prepare_webtest
ci/qa/webtests
composer.json
tests/webtests/EntityDeleteTest.php
tests/webtests/EntityEditTest.php
tests/webtests/WebTestCase.php

The webtests regularly halt/timeout. This is an attempt to isolate these tests. Making them less prone to fail hopefully.

Chore: Run webtests in isolation

---

src/Surfnet/ServiceProviderDashboard/Application/CommandHandler/Entity/PublishEntityProductionCommandHandler.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/GeneratorInterface.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/JsonGeneratorStrategy.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OauthClientCredentialsClientJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Application/Metadata/OidcngResourceServerJsonGenerator.php
src/Surfnet/ServiceProviderDashboard/Domain/Entity/Entity/EntityEditRevisionNote.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/Manage/Client/PublishEntityClient.php
tests/unit/Application/Metadata/JsonGeneratorStrategyTest.php
tests/unit/Application/Metadata/JsonGeneratorTest.php
tests/unit/Application/Metadata/OidcngJsonGeneratorTest.php
tests/unit/Application/Metadata/OidcngResourceServerJsonGeneratorTest.php

See: https://www.pivotaltracker.com/story/show/187992345

Add detailed revision note when editing an entity

---

src/Surfnet/ServiceProviderDashboard/Domain/ValueObject/EntityConnectionExport.php

See: https://www.pivotaltracker.com/story/show/187805216/comments/241955945

Stylize the entity connection CSV column names

---

src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
templates/Service/my-services.html.twig

See: https://www.pivotaltracker.com/story/show/186881796/comments/241954253

Translate the 'service connections' table headers

---

assets/js/application.js
assets/js/components/table_filter.ts
assets/js/components/table_filter_logic.test.ts
assets/js/components/table_filter_logic.ts
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/IdpEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
templates/form/fields.html.twig

Prior to this change, on a very long list with idp's it was difficult to find the idp you are looking for.
This change improves the idp selection UX by adding a search bar that searches in the table.
See https://github.com/SURFnet/sp-dashboard/issues/1332

Add the ability to filter the Entity IDP selection list

---

CHANGELOG.md
assets/js/application.js
assets/js/components/table_filter.ts
assets/js/components/table_filter_logic.test.ts
assets/js/components/table_filter_logic.ts
assets/scss/pages/base.scss
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveOidcngEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/SaveSamlEntityCommand.php
src/Surfnet/ServiceProviderDashboard/Application/Command/Entity/UpdateEntityIdpsCommand.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/IdpEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/OidcngEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Form/Entity/SamlEntityType.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/messages.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Resources/translations/validators.en.yml
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelected.php
src/Surfnet/ServiceProviderDashboard/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelectedValidator.php
templates/EntityAcl/idps.html.twig
templates/form/fields.html.twig
tests/integration/Infrastructure/DashboardBundle/Validator/Constraints/AtLeastOneSelectedValidatorTest.php
tests/webtests/EntityCreateOidcngTest.php
tests/webtests/EntityCreateSamlTest.php
tests/webtests/EntityEditTest.php

This resolves the merge conflict in changelog.md. Will close https://github.com/SURFnet/sp-dashboard/pull/1339

Resolve conflicts and merge latest 6.2 release into main 

---

CHANGELOG.md

Important changes are already in main. Just update the changelog.
Will close https://github.com/SURFnet/sp-dashboard/pull/1327

Resolve conflicts and merge latest 6.0 release into main

---

composer.json
composer.lock

From:
https://github.com/lesstif/php-jira-rest-client/pull/548/files

merge upstream experimental fix
